feat(connectors): add replacing deprecated template guide
camunda/camunda-docs pull request #1252
Opened 2022-09-13 05:51 UTC by Oleksiivanov

## What is the purpose of the change

_Briefly describe the change you are making, this helps the reviewer by providing an overview._
Write documentation on migrating to dynamic templates #1249

## Are there related marketing activities
https://github.com/camunda/camunda-platform-docs/issues/1249
_Are there any marketing activities related to the related feature or component? If so, please briefly describe them._
https://github.com/camunda/team-connectors/issues/93
## When should this change go live?

_Does this change need to be released before a certain date or milestone? If so, when?_

ASAP would be ideal.

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-09-13 08:34 UTC, igpetrov commented
@PreetiNirwal: "let's keep it generic" - note from daily

2022-09-13 15:01 UTC, christinaausley commented
@Oleksiivanov Are you looking for my review here as well? If so, feel free to request it when you're ready 👍

2022-09-14 14:20 UTC, PreetiNirwal commented on docs/components/integration-framework/connectors/out-of-the-box-connectors/rest.md
> +
@Oleksiivanov no need to add these sentence to REST Connector docs. 
You can remove entire: 

"If you see that connector mark as 'Deprecated', you can update and replace it.
See [Replacing Templates](../../../../components/modeler/desktop-modeler/element-templates/using-templates.md) for more."

2022-09-14 14:21 UTC, PreetiNirwal commented on docs/components/integration-framework/connectors/out-of-the-box-connectors/sendgrid.md
> +
@Oleksiivanov same as above, no need to add these sentence to SendGrid Connector docs.
You can remove entire:

"If you see that connector mark as 'Deprecated', you can update and replace it.
See [Replacing Templates](https://github.com/components/modeler/desktop-modeler/element-templates/using-templates.md) for more."

2022-09-14 14:31 UTC, PreetiNirwal requested changes
See comments. No need to update rest.md & sendgrid.md files.

2022-09-14 14:47 UTC, PreetiNirwal approved these changes
Looks good! Thanks.

2022-09-14 15:22 UTC, merged

2022-09-14 23:10 UTC, PreetiNirwal commented
Hi @akeller, if we can merge this PR to the 8.0 docs when possible, that'd be great. Thanks.

2022-09-15 14:02 UTC, akeller commented
Looks like this got merged without a review from the docs side. @christinaausley can you review this an open a separate PR with any adjustments?

2022-09-16 14:03 UTC, akeller commented
> Hi @akeller, if we can merge this PR to the 8.0 docs when possible, that'd be great. Thanks.

@PreetiNirwal because these changes went into `/docs/` they will be available in `Next` (aka 8.1). Should this be available in the current docs (8.0)?

2022-09-16 14:06 UTC, PreetiNirwal commented
Hi @akeller - this one we would like in 8.0. Hope that doesn't add complexity.

2022-09-16 14:07 UTC, akeller commented
Nope, I'll take care of it 🙂