feat(connectors): add Microsoft Teams Connector documentation
camunda/camunda-docs pull request #1556
Opened 2022-12-05 18:23 UTC by Oleksiivanov

## What is the purpose of the change

add Microsoft Teams Connector documentation

This is draft PR, move to ready for review after https://github.com/camunda/connector-microsoft-teams/issues/3 and https://github.com/camunda/connector-microsoft-teams/issues/4

Link for more comfortable review this docs : https://github.com/camunda/camunda-platform-docs/blob/add_microsoft_teams_documantation/docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md

## Are there related marketing activities

https://github.com/camunda/team-connectors/issues/211

## When should this change go live?

todo

## PR Checklist

- [ ] My changes apply to an already released version, and I have added them to the relevant `/versioned_docs` directory, or they are not for an already released version.
- [ ] My changes apply to future versions, and I have added them to the main `/docs` directory, or they are not for future versions.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-platform-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2022-12-09 08:54 UTC, igpetrov requested changes
What about limitations? AFAIK, you can only send messages with a bearer token but not with client credentials, or did you resolve that?

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +relevant [Microsoft Graph API permissions](https://learn.microsoft.com/en-us/graph/permissions-reference).
```suggestion
the relevant [Microsoft Graph API permissions](https://learn.microsoft.com/en-us/graph/permissions-reference).
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +First, you must have a user account in Microsoft Teams with the necessary permissions. See more at
```suggestion
First, you must have a user account with the Microsoft Teams with the necessary permissions. See more at
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +the [Microsoft Teams overview](https://learn.microsoft.com/microsoftteams/teams-overview). If you are not have
```suggestion
the [Microsoft Teams overview](https://learn.microsoft.com/microsoftteams/teams-overview). If you don't have
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +administration role and permissions ask your Microsoft Teams administrator to add needed permissions for work with
```suggestion
administration role and permissions ask your Microsoft Teams administrator to add required permissions for work with
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +Microsoft Teams Connector.
```suggestion
the **Microsoft Teams Connector**.
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +- More information about Microsoft Graph auth you can find here : [Microsoft Graph auth overview](https://learn.microsoft.com/en-us/graph/auth/)
```suggestion
- More information about the Microsoft Graph API authentication you can find here : [Microsoft Graph auth overview](https://learn.microsoft.com/en-us/graph/auth/)
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +See more about [Microsoft Teams Access Token](https://learn.microsoft.com/azure/active-directory/develop/access-tokens);
```suggestion
See more about [Microsoft Teams Access Token](https://learn.microsoft.com/azure/active-directory/develop/access-tokens).
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +#### A few ways for getting Access Token :
```suggestion
#### Options to obtain an access token
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +   - How to get access without a user you can read here : [Get access without a user](https://learn.microsoft.com/en-us/graph/auth-v2-service)
```suggestion
1. Via the graph explorer
   - Visit [developer.microsoft.com/graph/graph-explorer](https://developer.microsoft.com/graph/graph-explorer)
   - Login with your Microsoft account
   - Choose tab 'Access Token' and copy the bearer token
   
![connectors-microsoft-teams-copy-token](../img/connectors-microsoft-teams-copy-token.png)

2. Register your app with the Microsoft identity platform and send a POST request to the `/token` identity platform endpoint to acquire an access token
   - How to register your App: [Register your app](https://learn.microsoft.com/en-us/graph/auth-register-app-v2)
   - How to get access on behalf of a user: [Get access on behalf of a user](https://learn.microsoft.com/en-us/graph/auth-v2-user)
   - How to get access without a user: [Get access without a user](https://learn.microsoft.com/en-us/graph/auth-v2-service)
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +2. Set **Tenant id** to `Tenant ID`. (Your Microsoft Teams tenant ID is a unique identifier. See more [How to find Tenant ID](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/act
```suggestion
2. Set **Tenant id** to `Tenant ID`. (Your Microsoft Teams tenant ID is a unique identifier. See more about [how to find a tenant ID](https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant))
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +3. Set **Client id** to `Client ID`. (The application ID that the [Azure app registration portal](https://go.microsoft.com/fwlink/?linkid=2083908) assigned to your app.)
```suggestion
3. Set **Client id** to `Client ID`. (The application ID that the [Azure app registration portal](https://go.microsoft.com/fwlink/?linkid=2083908) assigned to your app)
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +4. Set **Secret id** to `Secret ID`. (The client secret that you created in the app registration portal for your app)
```suggestion
4. Set the **Secret ID** field: the client secret that you created in the app registration portal for your app
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +3. Set **Client id** to `Client ID`. (The application ID that the [Azure app registration portal](https://go.microsoft.com/fwlink/?linkid=2083908) assigned to your app.)
```suggestion
3. Set the **Client ID** field: the application ID that the [Azure app registration portal](https://go.microsoft.com/fwlink/?linkid=2083908) assigned to your app
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +In the **Operation** section you could choose conversation type, for now it is **Chat** and **Channel**, after that you need choose one of suggestion method :
```suggestion
In the **Operation** section you could choose a conversation type, either **Chat**, or **Channel**, after that you need to choose one of suggested method:
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +![todo add gif](../img/connectors-microsoft-teams-choose-method.gif)
```suggestion
![MS Teams Choose Method](../img/connectors-microsoft-teams-choose-method.gif)
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +For example, if you want to send message in Microsoft Teams channel, you need choose conversation type **Channel** and method **Send message in channel**
```suggestion
For example, if you want to send a message in Microsoft Teams channel, you need choose conversation type **Channel** and method **Send message in channel**
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +#### Properties:
```suggestion
#### Properties
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +Example :
```suggestion
Example:
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +#### Methods:
```suggestion
#### Methods
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +#### Properties:
```suggestion
#### Properties
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +#### Methods:
```suggestion
#### Methods
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +The **Microsoft Teams Connector** returns the Microsoft Graph API response in 'result' wrapper:
```suggestion
The **Microsoft Teams Connector** returns the Microsoft Graph API response in `result` wrapper:
```

2022-12-09 08:54 UTC, igpetrov commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +See [channel resource type](https://learn.microsoft.com/graph/api/resources/channel?view=graph-rest-1.0) for find response on needed method for channel conversation type or see [chat resource type](h
```suggestion
See [channel resource type](https://learn.microsoft.com/graph/api/resources/channel?view=graph-rest-1.0) to find response for the required method for a channel conversation type or see [chat resource type](https://learn.microsoft.com/graph/api/resources/chat?view=graph-rest-1.0) to find response for the required method for a chat conversation type.
```

2022-12-12 13:00 UTC, igpetrov commented
@Oleksiivanov is this ready for review?

2022-12-12 13:04 UTC, igpetrov commented
@Oleksiivanov please keep in mind that the build is failing

2022-12-14 18:18 UTC, christinaausley requested changes
Technical review in latest commit for wording, grammar, punctuation, and more. Let me know if you have any questions about these changes.

Additionally, I had a few comments regarding an abbreviation and the FAQ section.

2022-12-14 18:18 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +|      Display name       |                                                                                     Create channel
When you say "MS teams channel" do you mean Microsoft Teams channel? If so, I would spell this out formally.

2022-12-14 18:18 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +|          Owner          |                                                                Create channel (if Channel membership type != STANDARD)
Same comment here.

2022-12-14 18:18 UTC, christinaausley commented on docs/components/connectors/out-of-the-box-connectors/microsoft-teams.md
> +## Appendix & FAQ
As this is mentioned on line 18 and users are directed here, and then again directed to managing secrets, would it be better to remove this appendix section and on line 18 just say something like:
:::note
It is highly recommended to use Camunda secrets to store credentials so you don't expose sensitive information directly from the process. See [managing secrets](../../../components/console/manage-clusters/manage-secrets.md) to learn more.
:::

2022-12-19 21:28 UTC, pepopowitz commented
Hi! This PR is currently in a "frozen" state, with merging blocked due to [a new `enforce-label` check](https://github.com/camunda/camunda-platform-docs/pull/1578) not having run.

This is fixable! If you rebase on `main`, or merge `main`, this branch will get the changes it needs to run that check. This PR has a `hold` label, so when that check runs it will put the PR in a _different_ un-mergeable state -- but at least that one will be correct! 

If you'd prefer, @akeller or myself have the ability to check a box to merge without the check running. If/when you've got the reviews you need and you want us to merge for you, just let us know.

2022-12-20 17:07 UTC, christinaausley approved these changes
Thanks for resolving my comments! 👍

2022-12-23 10:41 UTC, igpetrov approved these changes
LGTM

2022-12-23 10:44 UTC, merged