Correct button copy
camunda/camunda-docs pull request #2731
Opened 2023-10-11 15:07 UTC by jprcoliveira

## Description

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2023-10-11 15:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda/camunda-docs?pullRequest=2731) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda/camunda-docs?pullRequest=2731) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda/camunda-docs?pullRequest=2731) it.</sub>

2023-10-11 16:53 UTC, akeller reviewed
Should this be in `/docs/` as well? So it shows up for 8.4 or the preview versions?

2023-10-11 16:54 UTC, jprcoliveira commented
> Should this be in `/docs/` as well? So it shows up for 8.4 or the preview version?

I was working on it. My browser just crashed. Now should be good.

2023-10-11 16:55 UTC, jprcoliveira commented
Should be good to go now @akeller

2023-10-11 16:59 UTC, akeller approved these changes

2023-10-11 19:40 UTC, christinaausley requested changes
Two comments 👍

2023-10-11 19:40 UTC, christinaausley commented on docs/components/console/manage-plan/retrieve-invoices-or-update-billing-info.md
Should line 19 be adjusted as well?

2023-10-11 19:40 UTC, christinaausley commented on versioned_docs/version-8.3/components/console/manage-plan/retrieve-invoices-or-update-billing-info.md
Same here for line 19 👍

2023-10-16 14:56 UTC, christinaausley commented
@jprcoliveira I adjusted line 19 but let me know if this was a mistake and can adjust in a subsequent PR 👍

2023-10-16 14:56 UTC, christinaausley approved these changes

2023-10-16 15:27 UTC, merged