Added table about message correlation
camunda/camunda-docs pull request #2960
Opened 2023-11-28 13:39 UTC by jonathanlukas

## Description

The new section contains a table that explains message behavior as the publishMessage command is funny.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2023-12-01 16:15 UTC, christinaausley commented
Is this only for the `next` version of documentation? I noticed this is already available but undocumented -- does this belong in any versioned docs as well?

2023-12-07 10:01 UTC, koevskinikola requested changes
Thanks for adding this @jonathanlukas!

The table looks pretty good. I added some feedback and some things to clarify before I approve the changes.

2023-12-07 10:01 UTC, koevskinikola commented on docs/components/concepts/messages.md
> +| empty string    | set        | set < 0      | Intermediate event | The message is correlated during lifetime of the message if a matching subscription to the empty string is active and there is no
:wrench: Typo suggestion:
```suggestion
| empty string    | set        | set < 0      | Intermediate event | The message is correlated during the lifetime of the message if a matching subscription to the empty string is active and there is no equal message in the buffer.           |
```

2023-12-14 12:39 UTC, jonathanlukas commented on docs/components/concepts/messages.md
I added a link to each occurence that points to the paragraph _Message uniqueness_ which explains it

2023-12-14 12:57 UTC, christinaausley approved these changes

2023-12-14 14:18 UTC, jonathanlukas commented
Oh yes @christinaausley . I will would like to wait for final approval and then replicate the new content to old versions of this page (including all until 8.1).

2023-12-15 08:29 UTC, koevskinikola submitted a review, later dismissed
LGTM @jonathanlukas :tada:

2023-12-15 15:16 UTC, christinaausley approved these changes

2023-12-15 15:16 UTC, merged