Add privileges for ES
camunda/camunda-docs pull request #3240
Opened 2024-01-22 17:42 UTC by akeller

## Description

@romansmirnov how far can I backport this change? All supported versions? 

Closes #3224. 

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-01-22 19:22 UTC, romansmirnov requested changes
Thanks for opening the PR. I have added a comment on the cluster privileges.

2024-01-22 19:22 UTC, romansmirnov commented on docs/self-managed/operational-guides/configure-elasticsearch-privileges.md
> +- `manage_ilm` when ILM is enabled
These three are not required for taking a backup.

* `monitor` is necessary for the health check
* `manage_index_templaces` are kind of to create the index schema on startup (if they don't exist yet in Elasticsearch)
* `manage_ilm` when the index lifecycle management is used to apply a retention policy


I think I would mark the first (monitor) and the second manage_index_templaces privilege as required. The third only when they apply ILM.

2024-01-22 21:19 UTC, akeller commented
@christinaausley I realized we won't have info in here about configuring ES privileges, so it feels weird to place this file in the **Operational guides** section. Do you have another suggestion? 

For additional context, ES is used by multiple components in Self-Managed. This could be a reference topic, but it's not for SaaS users.

2024-01-23 20:54 UTC, akeller commented
> Could we not fit this into Concepts? I feel like we've been having a handful of "Where does this misc doc go in SM?" conversations. Could always launch a sidebar section of additional resources that apply to all Self-Managed components, but IMO this is the goal of Concepts, no?

Yes! What a great idea. I was too stuck in thinking this was config and, therefore, must be a guide.

2024-01-29 12:53 UTC, romansmirnov submitted a review, later dismissed
@akeller, LGTM! I believe the ILM privileges are not required with 8.1 and 8.2 - I went through the change logs to prove.

2024-01-29 12:53 UTC, romansmirnov commented on versioned_docs/version-8.1/self-managed/concepts/elasticsearch-privileges.md
> +- _Optional_ `manage_ilm` - required only when ILM is enabled
```suggestion
```

Not required with 8.1.

2024-01-29 12:53 UTC, romansmirnov commented on versioned_docs/version-8.1/self-managed/concepts/elasticsearch-privileges.md
> +- _Optional_ `manage_ilm` - required only when ILM is enabled
```suggestion
```
Not required with 8.1.

2024-01-29 12:53 UTC, romansmirnov commented on versioned_docs/version-8.2/self-managed/concepts/elasticsearch-privileges.md
> +- _Optional_ `manage_ilm` - required only when ILM is enabled
```suggestion
```
Not required with 8.2.

2024-01-29 12:53 UTC, romansmirnov commented on versioned_docs/version-8.2/self-managed/concepts/elasticsearch-privileges.md
> +- _Optional_ `manage_ilm` - required only when ILM is enabled
```suggestion
```
Not required with 8.2.

2024-01-29 13:24 UTC, romansmirnov commented on versioned_docs/version-8.2/self-managed/concepts/elasticsearch-privileges.md
> +- _Optional_ `manage_ilm` - required only when ILM is enabled
I was wrong! It is available with 8.2

2024-01-29 13:24 UTC, romansmirnov commented on versioned_docs/version-8.2/self-managed/concepts/elasticsearch-privileges.md
> +- _Optional_ `manage_ilm` - required only when ILM is enabled
I was wrong! It is available with 8.2

2024-01-31 14:23 UTC, akeller commented
@christinaausley can I get a review from you and a 👍 so I can merge?

2024-01-31 15:26 UTC, christinaausley approved these changes

2024-01-31 16:04 UTC, merged