feat: integrate kapa.ai into docs
camunda/camunda-docs pull request #3241
Opened 2024-01-22 17:59 UTC by pepopowitz

Addresses https://github.com/camunda/developer-experience/issues/202

## Description

Integrates the Kapa.ai "Ask AI" widget.

Kudos to the Kapa team for making this super easy to implement.

### What it looks like

(note that I had to truncate this video in order to get it small enough to upload)

https://github.com/camunda/camunda-docs/assets/1627089/079176e7-4778-4e75-bb78-1add0a49d97f

### Configuration options

I didn't see anything I thought we should change in the configuration, but if you see anything you'd like changed, [these are the available configuration options](https://docs.kapa.ai/installation-widget#optional-configuration-parameters-).

### Preview site?

I haven't pushed this up to a preview site yet, and I'm not sure I will -- let me know in the comments if you think that would be valuable!

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [x] This change or page is part of a marketing blog, conference talk, or something else on a schedule. Should be live by end of this week (Jan 22 - 26).
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-01-22 19:54 UTC, christinaausley commented
Obsessed.

2024-01-22 19:55 UTC, christinaausley submitted a review, later dismissed

2024-01-22 21:03 UTC, akeller requested changes
I'm "requesting changes" because we are waiting for final disclaimer copy and I'd like to change the questions. See https://camunda.slack.com/archives/C05MCG4GQET/p1705951641269069 to follow the thread.

2024-01-23 09:34 UTC, MoAtCamunda commented
Disclaimer text:

Welcome to Camunda 8 Smart docs, powered by AI.  Accessing  developer docs, forum posts and product blogs from the last year, responses are generated by combining various sources to formulate the best possible answer. If you have feedback please give a thumbs up or down as we continue to improve the AI.

2024-01-23 20:35 UTC, pepopowitz commented on docusaurus.config.js
> +      "data-modal-example-questions": `How do I get started with Camunda 8?,What is new in Camunda ${latestVersion}?`,
This will prevent me from doing a panic-release after each new version, as we realize the sample question has become out of date.

2024-01-23 20:36 UTC, pepopowitz commented
Disclaimer and sample questions have been updated based on conversations here & in Slack. If we decide on other sample questions, let me know.

2024-01-24 20:46 UTC, akeller approved these changes

2024-01-24 20:51 UTC, pepopowitz commented
Merging as-is, and we may come back with more sample question changes based on Slack conversations.

2024-01-24 20:51 UTC, merged