docs(web-modeler): document file download and export options
camunda/camunda-docs pull request #3309
Opened 2024-02-09 16:58 UTC by jfriedenstab

## Description
Documents the file download and export options in Web Modeler.

Closes https://github.com/camunda/web-modeler/issues/5286.

## When should this change go live?

- [x] This change is not yet live and should not be merged until Feb 13 (`8.5.0-alpha1` release date) (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [x] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-02-11 21:44 UTC, HanselIdes requested changes
Overall LGTM - I suggested some ways to clarify the value and shorten the text. Overall, the UI for this kind of feature should be self-explanatory enough that documentation can be light. The main 'gotchas' were covered nicely: the download limit and different behavior between project view and file editor view.

You do not need to re-request my review.

2024-02-11 21:44 UTC, HanselIdes commented on docs/components/modeler/web-modeler/file-download.md
> +For BPMN diagrams, you also have the option to export them in different image formats.
```suggestion
You may also export BPMN diagrams in different image formats.
```
suggestion for brevity

2024-02-11 21:44 UTC, HanselIdes commented on docs/components/modeler/web-modeler/file-download.md
> +You can download all the files stored in Web Modeler to your local computer.
```suggestion
You can download all the files stored in Web Modeler to your local computer for offline editing or integration into version control.
```
introduces the main use cases for download

2024-02-12 16:05 UTC, christinaausley approved these changes
Nice writing here!

2024-02-12 16:23 UTC, jfriedenstab commented
@HanselIdes To allow me to merge the PR, I think you need to approve it (because you requested changes).

2024-02-12 19:21 UTC, merged