docs(announcements): web-modeler beta api removal
camunda/camunda-docs pull request #3503
Opened 2024-03-22 08:01 UTC by JacobiCamunda

## Description

As part of the [removal of the Web Modeler beta API](https://github.com/camunda/web-modeler/issues/8250), an announcement for 8.5 should be made.

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-03-22 08:10 UTC, JacobiCamunda commented
@christinaausley, I would like to remove [this section](https://docs.camunda.io/docs/next/apis-tools/web-modeler-api/overview/#migrating-from-beta-to-v1) for the versioned docs `8.5` but there is no versioned docs for `8.5` yet. When will it be added?

2024-03-22 16:01 UTC, christinaausley commented
Hi @JacobiCamunda -- anything added to `next` will become the `8.5` version upon release in April. These are the docs in the `docs` folder as opposed to the `versioned_docs` folder.

2024-04-02 07:23 UTC, wollefitz requested changes

2024-04-02 07:23 UTC, wollefitz commented on docs/reference/announcements.md
> +For a migration guide, see the [Web Modeler API documentation](/apis-tools/web-modeler-api/index.md#migrating-from-beta-to-v1).
❌ This link doesn't work because within this PR, you removed the section which is linked here.

2024-04-02 07:23 UTC, wollefitz commented on docs/apis-tools/web-modeler-api/index.md
> -:::
I'd propose keeping this section for the `8.5` docs and only remove it for the future `next`/`8.6` once `8.5` has been released.

We can rephrase the section a bit to make it clearer that the beta api was removed:

```
### How do I migrate from the `beta` API to the `v1` API? {#migrating-from-beta-to-v1}

Web Modeler's beta API was removed in this release.
To migrate to `v1`, change the base URL from `/api/beta` to `/api/v1`.

:::caution Breaking changes

- `GET /api/beta/projects/{projectId}/files` was removed. Use `POST /api/v1/files/search` instead.
- `GET /api/beta/files/{fileId}/milestones` was removed. Use `POST /api/v1/milestones/search` instead.
- `GET /api/beta/projects` was removed. Use `POST /api/v1/projects/search` instead.

:::

Refer to the [OpenAPI documentation](#openapi-documentation) for details.
```

2024-04-04 14:45 UTC, christinaausley approved these changes

2024-04-04 14:51 UTC, wollefitz approved these changes

2024-04-04 14:52 UTC, christinaausley commented
Feel free to merge when you're ready @JacobiCamunda 👍

2024-04-04 14:55 UTC, merged