Update Local deployment guide with connectivity topics
camunda/camunda-docs pull request #3509
Opened 2024-03-22 16:25 UTC by theburi

## Description

My goal is to improve the local deployment guide to help users do E2E

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-03-26 15:09 UTC, christinaausley requested changes
A few comments to clarify a few sections.

Additionally, I'm not sure we need to break this up into tabs. I think we can keep everything within a single file here, particularly given the trouble we've been having with deep-linking to tabbed content lately.

2024-03-26 15:25 UTC, theburi commented on docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
> +First, port-forward each of the components. Use a separate terminal for each command. Then, each component can be accessed at `http://localhost:PORT` (for example, Optimize will have the address `htt
rephrased

2024-03-26 15:30 UTC, theburi commented on docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
> +Proceed to install the Camunda Helm chart [Deploy](#deploy)
Yes, I slightly modified this sentence. Let me know if it works.

2024-03-26 15:31 UTC, theburi commented on docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
> +At this stage, you should consider how to connect to the future Camunda 8 cluster. If you are setting up Camunda 8 for the first time, we recommend using **port-forwarding**, in which case you may co
What do you mean?

2024-03-26 15:36 UTC, theburi commented
> A few comments to clarify a few sections.
> 
> Additionally, I'm not sure we need to break this up into tabs. I think we can keep everything within a single file here, particularly given the trouble we've been having with deep-linking to tabbed content lately.

I find one large file gets newcomers confused as it's hard to follow, and ignore sections. Tabs create a single flow, hiding sections and avoiding confusion.
In this particular case, we would not link to these tabs as we have other articles explaining these topics in all detail.

2024-03-26 16:34 UTC, christinaausley commented on docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
> +At this stage, you should consider how to connect to the future Camunda 8 cluster. If you are setting up Camunda 8 for the first time, we recommend using **port-forwarding**, in which case you may co
Similar to linking to the other sections in the doc, I would link to "port-forwarding" and "ingress".

2024-03-26 17:14 UTC, theburi commented on docs/self-managed/platform-deployment/helm-kubernetes/guides/local-kubernetes-cluster.md
> +At this stage, you should consider how to connect to the future Camunda 8 cluster. If you are setting up Camunda 8 for the first time, we recommend using **port-forwarding**, in which case you may co
I made a change and I added a link that seems to work on my local build.

2024-04-01 15:00 UTC, christinaausley commented
Is this linked to a particular issue and is this for `next` or the `8.5` release only?

2024-04-01 15:00 UTC, christinaausley approved these changes

2024-04-02 12:45 UTC, jessesimpson36 approved these changes

2024-04-03 01:18 UTC, aabouzaid approved these changes
LGTM, thank you :+1:

2024-04-05 10:45 UTC, merged