feat(modeler): document boolean and number template types
camunda/camunda-docs pull request #3661
Opened 2024-04-15 09:20 UTC by marstamm

## Description

This PR adds documentation for new element template features: number and boolean types as well as the `feel: static` option.
This was released with 8.5 but not documented.

related to https://github.com/bpmn-io/internal-docs/issues/919

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [x] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [x] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [x] I have added changes to the relevant `/versioned_docs` directory
- [x] I have added changes to the main `/docs` directory (aka `/next/`)
- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-04-15 09:42 UTC, barmac requested changes

2024-04-15 09:42 UTC, barmac commented on versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md
>        "label": "Required FEEL Expression",
It's optional.

2024-04-15 09:42 UTC, barmac commented on docs/components/modeler/desktop-modeler/element-templates/defining-templates.md
>        "label": "Required FEEL Expression",
```suggestion
      "label": "Optional FEEL Expression",
```

2024-04-15 09:42 UTC, barmac commented on versioned_docs/version-8.5/components/modeler/desktop-modeler/element-templates/defining-templates.md
>        "label": "Required FEEL Expression",
```suggestion
      "label": "Optional FEEL Expression",
```

2024-04-16 17:00 UTC, christinaausley approved these changes

2024-04-17 07:25 UTC, merged