docs(spring-zeebe-sdk): add repo for identity sdk
camunda/camunda-docs pull request #3667
Opened 2024-04-15 14:27 UTC by nicpuppa

## Description

Spring Zeebe SDK users should add a repo into their Maven `settings.xml` file in order to make it works

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-04-15 15:00 UTC, megglos requested changes
Thanks for getting this ready right away! One suggestion to actually recommend adding it to the projects pom, would be less invasive to the overall maven setup and portable.

2024-04-15 15:07 UTC, nicpuppa commented on docs/apis-tools/spring-zeebe-sdk/getting-started.md
> +Add the following repository to your Maven `settings.xml`
I wasn't aware of this, thanks

2024-04-15 16:00 UTC, ana-vinogradova-camunda submitted a review, later dismissed
Thanks for addressing that 🚀

2024-04-16 08:25 UTC, megglos approved these changes
LGTM! Pre-approved just one suggestion.

2024-04-16 08:25 UTC, megglos commented on docs/apis-tools/spring-zeebe-sdk/getting-started.md
> +</repository>
🔧 for a better UX let's also add the `<repositories>` wrapper here, so someone could just c&p the snippet into their pom.
```suggestion
<repositories>
    <repository>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>identity</id>
       <name>Camunda Identity</name>
        <url>https://artifacts.camunda.com/artifactory/camunda-identity/</url>
    </repository>
</repositories>
```

2024-04-16 08:25 UTC, megglos commented on versioned_docs/version-8.5/apis-tools/spring-zeebe-sdk/getting-started.md
> +</repository>
```suggestion
```suggestion
<repositories>
    <repository>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <id>identity</id>
       <name>Camunda Identity</name>
        <url>https://artifacts.camunda.com/artifactory/camunda-identity/</url>
    </repository>
</repositories>
```
```

2024-04-16 12:26 UTC, ana-vinogradova-camunda approved these changes

2024-04-16 12:26 UTC, merged