Document soft pause exporter.
camunda/camunda-docs pull request #3720
Opened 2024-04-25 21:24 UTC by rodrigo-lourenco-lopes

## Description

This PR adds documentation for the soft pause exporter. 
This also affects versions 8.3, 8.4, and 8.5.

closes https://github.com/camunda/zeebe/issues/17424

## When should this change go live?

- [ ] This change is not yet live and should not be merged until {ADD_DATE} (apply `hold` label or convert to draft PR)?
- [ ] There is no urgency with this change.
- [ ] This change or page is part of a marketing blog, conference talk, or something else on a schedule.
- [ ] This functionality is already available but undocumented.
- [ ] This is a bug fix or security concern.

## PR Checklist

- [ ] I have added changes to the relevant `/versioned_docs` directory, or they are not for an **already released version**.
- [ ] I have added changes to the main `/docs` directory (aka `/next/`), or they are not for **future versions**.
- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned an engineering manager or tech lead as a reviewer, or my changes do not require an Engineering review.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer, or my changes do not require a technical writer review.

2024-04-26 08:40 UTC, deepthidevaki requested changes

2024-04-26 08:40 UTC, deepthidevaki commented on docs/self-managed/zeebe-deployment/operations/management-api.md
> +Another option is to use the soft pause feature, which enables us to continue to export records without updating the last acknowledged record position. This allows us to continue to export data to ES
I would suggest to add a separate section for soft pause. 

For the explanation, I would write something along the lines of the following. No need to mention last acknowledged position: 

Soft pause feature can be used when you want to continue exporting records but do not want to delete those records (log compaction) from zeebe. This is particularly useful during hot backups. How to use this feature for hot backups is documented [here](link to hot backup docs).

2024-04-30 14:48 UTC, deepthidevaki approved these changes
Thanks

2024-04-30 16:40 UTC, merged

2024-04-30 20:38 UTC, christinaausley commented
Oops! I think we missed a documentation review here. I'll do a retro review, but do loop me in for any additional docs changes before we merge moving forward 👍 I can usually get around to them in a day or two.