docs(requirements): update optimize requirement with Java 21
camunda/camunda-docs pull request #3741
Opened 2024-04-30 10:24 UTC by buccarel

## Description

Optimize is dropping the support for Java 17 and 20, in favor of Java 21.
With this PR, the documentation will be updated accordingly.
Issue: https://github.com/camunda/camunda-optimize/issues/12541

## When should this change go live?
Contextually with the release of Optimize 3.14 (scheduled for 8th of October 2024)

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineerring DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

2024-04-30 16:52 UTC, RomanJRW requested changes
Thanks for doing the docs for this too!

2024-04-30 16:52 UTC, RomanJRW commented on versioned_docs/version-8.5/reference/supported-environments.md
> +| Optimize    | OpenJDK 21+  | Elasticsearch 8.9+<br/>Amazon OpenSearch 2.5.x
these are versioned docs for 8.5. Given that we don't want to backport this, let's not change this file

2024-04-30 20:47 UTC, christinaausley commented
Hi 👋 

Is this a breaking change? Do we need to note this elsewhere in the docs, or in the announcements?

2024-05-02 19:56 UTC, RomanJRW commented
@christinaausley - is it enough that we announced it [here](https://github.com/camunda/camunda-docs-static/pull/463)? Or do you mean a different announcements page?

2024-05-06 18:49 UTC, merged