docs(optimize): document SNI configuration options
camunda/camunda-docs pull request #3788
Opened 2024-05-10 10:04 UTC by buccarel

## Description

Context:
https://github.com/camunda/camunda-optimize/issues/11941

With this PR, we are adding the documentation about the option to enable or disable the SNI check.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

2024-05-10 19:18 UTC, RomanJRW requested changes
Thanks for doing this, just a change in the default values please 🙂

2024-05-10 19:18 UTC, RomanJRW commented on optimize/self-managed/optimize-deployment/configuration/system-configuration.md
> +| container.enableSniCheck         | false         | Determines whether SNI checking should be enabled.
default is `true` 🙂

2024-05-10 19:18 UTC, RomanJRW commented on optimize_versioned_docs/version-3.10.0/self-managed/optimize-deployment/configuration/system-configuration.md
> +| container.enableSniCheck         | false         | Determines whether SNI checking should be enabled.
same as above

2024-05-10 19:18 UTC, RomanJRW commented on optimize_versioned_docs/version-3.11.0/self-managed/optimize-deployment/configuration/system-configuration.md
> +| container.enableSniCheck         | false         | Determines whether SNI checking should be enabled.
same as above

2024-05-10 19:18 UTC, RomanJRW commented on optimize_versioned_docs/version-3.12.0/self-managed/optimize-deployment/configuration/system-configuration.md
> +| container.enableSniCheck         | false         | Determines whether SNI checking should be enabled.
same as above

2024-05-10 19:18 UTC, RomanJRW commented on optimize_versioned_docs/version-3.13.0/self-managed/optimize-deployment/configuration/system-configuration.md
> +| container.enableSniCheck         | false         | Determines whether SNI checking should be enabled.
same as above

2024-05-13 15:31 UTC, akeller commented
@buccarel since we have an alpha release tomorrow, we'll do doing at least one docs release this week (later today). If you get this cleaned up, we can include it!

2024-05-13 21:55 UTC, RomanJRW commented
@buccarel has FTO for the next few days. Given that this is not new functionality, I don't see the need to find someone on the team to take over in his absence and it can wait until his return

2024-05-17 08:57 UTC, RomanJRW approved these changes

2024-05-17 08:58 UTC, merged