docs(api): add console sm admin api
camunda/camunda-docs pull request #3799
Opened 2024-05-14 12:50 UTC by urbanisierung

## Description

- Relates https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/2871

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @christinaausley as a reviewer.

2024-05-15 11:25 UTC, urbanisierung commented
@pepopowitz iirc you've introduced the interactive API explorer to the docs. Can you please have a quick look if anything is missing in this PR? Thanks!

2024-05-16 16:47 UTC, pepopowitz requested changes
This is really fantastic!!!

I have a couple small blocking requests, and one non-blocking. Overall, it's great, and I want to thank you for following the patterns in place and practically nailing this implementation. It looks really good.

I'm also curious if you have feedback for me on what it takes to add a new API Explorer. Were there challenges along the way that seemed frustrating or unnecessary? Any opportunities for improvement you noticed?

2024-05-16 16:47 UTC, pepopowitz commented on api/console-sm/console-sm-openapi.yaml
non-blocking recommendation: 

Descriptions on requests, responses, and fields provide helpful guidance in the generated API docs. A good illustration is to compare the docs generated from this spec (on the left) to the [Tasklist REST API docs](https://docs.camunda.io/docs/apis-tools/tasklist-api-rest/specifications/search-tasks/) (on the right): 

<img width="1789" alt="image" src="https://github.com/camunda/camunda-docs/assets/1627089/20f31ed3-69bc-4b54-afaa-8eeead87f8a7">


It's very likely that you're all thinking about this already, but I just wanted to provide another nudge to fill descriptions in. I have work lined up in the somewhat-near-future to follow up with OpenAPI specs that are lacking this data, and open PRs at the source; it's not my immediate priority, and if you accomplish that before I do that's great.

2024-05-17 06:34 UTC, urbanisierung commented on docs/apis-tools/console-sm-api/specifications/console-sm-admin-api.info.mdx
> +
Got it. By fixing the filename it was removed by the script.

2024-05-17 09:39 UTC, urbanisierung commented on api/console-sm/console-sm-openapi.yaml
@pepopowitz Thanks for the hints! I've updated our OpenAPI spec re descriptions:

![image](https://github.com/camunda/camunda-docs/assets/1721647/d3ae5876-f55c-4958-aa1b-fe8a22006499)

2024-05-17 09:44 UTC, urbanisierung commented
> I'm also curious if you have feedback for me on what it takes to add a new API Explorer. Were there challenges along the way that seemed frustrating or unnecessary? Any opportunities for improvement you noticed?

@pepopowitz I used a similar docusaurus plugin (maybe the same?) for one of my side project, so I already had same background knowledge what files to touch.

As a general improvement from my point of view:

* Our OpenAPI lib creates a json file. haven't tried the plugin with a `json` as input. If it's not supported it would be nice to have a built-in way within the docs repo to use also `json`, for example with a json-to-yaml converter (also available as npm module)
* What would be super cool: auto-fetching of OpenAPI spec instead of manually copying it. Our OpenAPI specs are (semi-) publicly available (via github or public url). The script could automatically fetch the latest content and update the docs.

2024-05-17 19:26 UTC, pepopowitz commented on api/console-sm/console-sm-openapi.yaml
Amazing, thank you!!!

2024-05-17 19:27 UTC, pepopowitz approved these changes
❤️ ❤️ ❤️ ❤️

2024-07-01 15:59 UTC, christinaausley commented
Hi @urbanisierung 😄 Is this still a WIP, or are you planning to make additional changes and/or looking for additional review?

2024-07-02 05:52 UTC, urbanisierung commented
> Hi @urbanisierung 😄 Is this still a WIP, or are you planning to make additional changes and/or looking for additional review?

@christinaausley Not planning to make any additional changes. Unfortunately I'm waiting for green lights from QA for this as well.

2024-07-30 05:40 UTC, urbanisierung commented
@christinaausley We finally got green lights from QA. The changes will be part of 8.6 alpha4 - can I just merge this one?

2024-07-30 17:00 UTC, merged

2024-08-05 14:26 UTC, christinaausley commented
@urbanisierung FYI that I'll get this into Postman for release next week.