docs(self-managed): mention the change of using image.tag
camunda/camunda-docs pull request #3999
Opened 2024-06-28 12:25 UTC by aabouzaid

## Description

Task: https://github.com/camunda/camunda-platform-helm/issues/2067

## When should this change go live?

- [x] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-06-28 15:12 UTC, conceptualshark submitted a review, later dismissed

2024-06-28 15:14 UTC, akeller requested changes

2024-06-28 15:14 UTC, akeller commented on docs/self-managed/setup/upgrade.md
> +With his change, Camunda applications no longer require a unified patch version. For example, a given installation may use Zeebe version 8.5.1, and Operate version 8.5.2. Note that only the patch ver
```suggestion
With this change, Camunda applications no longer require a unified patch version. For example, a given installation may use Zeebe version 8.5.1, and Operate version 8.5.2. Note that only the patch version can differ between components.
```

Just saw this typo. I did not do an exhaustive read-through of this PR, so there might be others.

2024-06-28 15:43 UTC, aabouzaid commented
@conceptualshark FYI, I just made a small change and added a deprecation note because that key will be actually removed as it's confusing and not needed anymore.

2024-06-28 16:49 UTC, conceptualshark approved these changes
Looks good on my end!

2024-07-01 14:29 UTC, akeller commented
Merging - this will get released later today with the alpha3 changes.

2024-07-01 14:29 UTC, merged