docs(concepts): Add documentation for Execution Listeners
camunda/camunda-docs pull request #4017
Opened 2024-07-04 08:02 UTC by ce-dmelnych

## Description

Relates to: https://github.com/camunda/camunda/issues/16219

This PR adds documentation for Execution Listeners (EL) in Camunda 8, providing developers with a guide on how to implement and utilize ELs effectively in their workflows. 

It includes the following sections:
- **Introduction**: Overview, benefits, and use cases of ELs.
- **Getting Started**: Steps to enable ELs in BPMN models.
- **Supported Elements**: A table of BPMN elements that support `start` and `end` ELs.
- **Parameters and Configuration**: Explanation of EL parameters and example configurations.
- **Limitations**: ELs limitations.
- **Usage**: How to define Job Workers to process EL jobs.
- **Variables**: Handling variables within ELs, including scope and dynamic variable handling.
- **Examples**: Some examples of EL usage.
- **Element Processing Flow**: A flowchart and detailed steps describing the lifecycle of elements with ELs.
- **FAQ**: Common questions and troubleshooting tips.
- **References**: Links to additional documentation.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-07-09 13:24 UTC, ce-dmelnych commented
> @ce-dmelnych Is this ready for review or not quite yet?

Hi @christinaausley ,

I have made some corrections, and the PR is now ready for review. However, it also requires an engineering review, so there might be some additional changes after that.

@saig0, could you please assist with the engineering review?

Thanks!

2024-07-17 18:15 UTC, christinaausley commented
@ce-dmelnych Cool 👍 I'll have a look after @saig0.

2024-08-02 14:12 UTC, saig0 requested changes
@ce-dmelnych thank you for writing the docs. It's a good start. :+1: 

However, I see the potential to make it more effective for users by rephrasing and restructuring some parts. I will schedule a meeting with you to discuss the improvements.

2024-08-02 14:12 UTC, saig0 commented on docs/components/concepts/execution-listeners.md
> +</details>
:wrench: This part is relevant to use EL correctly. We should not hide it.  

:wrench: We should make this part less technical and easier to understand for users.

2024-08-02 14:12 UTC, saig0 commented on docs/components/concepts/execution-listeners.md
> +  - Verify the configuration and ensure the element supports the specified listener type.
:wrench: No relevant information.

2024-08-02 14:12 UTC, saig0 commented on docs/components/concepts/execution-listeners.md
> +allowing for more informed decision-making and precise control over process flow.
:wrench: The usage of ELs and its technical base is most relevant for the user. We should move his part to the top.

:wrench: We should improve the wording to make it easier for users to understand.

2024-08-05 12:52 UTC, saig0 commented
@ce-dmelnych I pushed the changes from our review meeting today. :rocket:

2024-08-05 18:34 UTC, christinaausley approved these changes
This is so clean and well documented! Great work 🚀 

Should we also add this to the [glossary](https://docs.camunda.io/docs/reference/glossary/)?

2024-08-07 10:51 UTC, ce-dmelnych commented
Thank you both for your valuable reviews and the improvements you committed to the documentation! 🙌

@saig0 , I appreciate the meeting and the suggestions you provided, which have greatly enhanced the clarity and effectiveness of the content 🙇‍♂️ 

@christinaausley, thank you for your positive feedback!
I’ve just pushed another commit with some small improvements to the wording and formatting, fixed a broken link, and added the `Execution listener` term to the [glossary](https://preview.docs.camunda.cloud/pr-4017/docs/next/reference/glossary/#execution-listener). Please review it to see if it aligns with your expectations.

Thanks again for your support and collaboration! 🚀

2024-08-07 16:27 UTC, christinaausley approved these changes

2024-08-09 11:11 UTC, megglos commented
@saig0 @ce-dmelnych  do you consider it doable to get this merged by Tuesday next week? Will include a link in the release blogpost then.

2024-08-09 11:33 UTC, saig0 commented
@megglos yes. I'll review it on Monday.

2024-08-12 09:02 UTC, saig0 approved these changes
LGTM. :rocket:

2024-08-12 09:03 UTC, merged