Update node-js-sdk.md
camunda/camunda-docs pull request #4026
Opened 2024-07-11 03:41 UTC by jwulf

A customer reached out to support because they used the Docker profile with no Identity and the connection fails because we assume OAuth.

This patch informs the users how to turn OAuth off.

## Description

Ref: https://jira.camunda.com/browse/SUPPORT-22663

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ X ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ X ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ X ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-07-15 17:19 UTC, conceptualshark submitted a review, later dismissed

2024-07-15 20:57 UTC, pepopowitz requested changes
This looks good to me, except that I think the bot requesting corresponding changes in `docs/` is accurate. We should apply the update to version next, in addition to 8.5, to carry it forward into new releases.

2024-07-15 22:56 UTC, jwulf commented
> This looks good to me, except that I think the bot requesting corresponding changes in `docs/` is accurate. We should apply the update to version next, in addition to 8.5, to carry it forward into new releases.

Is that https://github.com/camunda/camunda-docs/pull/4027?

2024-07-16 14:57 UTC, pepopowitz commented
> > This looks good to me, except that I think the bot requesting corresponding changes in `docs/` is accurate. We should apply the update to version next, in addition to 8.5, to carry it forward into new releases.
> 
> Is that #4027?

Yes! Sorry, I didn't realize there was a second associated PR.

2024-07-16 14:57 UTC, pepopowitz approved these changes

2024-07-16 20:18 UTC, akeller commented on versioned_docs/version-8.5/apis-tools/node-js-sdk.md
> +If you are using the "basic components" (no Identity), you need to disable OAuth:
@christinaausley Josh will be out for the week on FTO. Can you discuss with @conceptualshark if you'd like to make this change?

2024-07-17 16:45 UTC, christinaausley approved these changes

2024-07-17 21:03 UTC, merged