chore(preview-envs): Look into improving commenting of preview enviro…
camunda/camunda-docs pull request #4060
Opened 2024-07-24 07:30 UTC by andromaqui

…nments

## Description

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-07-24 14:07 UTC, pepopowitz commented
@andromaqui can you add some details to the body of this PR, to explain how you're looking to improve the comments?

2024-07-24 15:04 UTC, kellervater commented
@andromaqui 
Looking good to me.
Just 2 minor things you could change:
* Remove message-id
* remove: repo-token
Both shouldn't be necessary to achieve your target.
You can lookup[ this PR](https://github.com/camunda/infra-global-github-actions/pull/228/files) for reference on how I used it.

I marked all spots via PR commentary.

2024-07-24 15:06 UTC, kellervater requested changes

2024-07-24 15:06 UTC, kellervater commented on .github/workflows/preview-env-deploy.yml
> +          message-id: preview-env-status
`message-id` is also not necessary, if you don't plan on having more than one comment you want to update throughout the process. There's a default value like `add-pr-comment`.

2024-07-24 15:06 UTC, kellervater commented on .github/workflows/preview-env-deploy.yml
> +          message-id: preview-env-status
`message-id` is also not necessary, if you don't plan on having more than one comment you want to update throughout the process. There's a default value like `add-pr-comment`.

2024-07-24 15:06 UTC, kellervater commented on .github/workflows/preview-env-deploy.yml
> +          message-id: preview-env-status
`message-id` is also not necessary, if you don't plan on having more than one comment you want to update throughout the process. There's a default value like `add-pr-comment`.

2024-07-24 15:06 UTC, kellervater commented on .github/workflows/preview-env-teardown.yml
> +          message-id: preview-env-status
`message-id` is also not necessary, if you don't plan on having more than one comment you want to update throughout the process. There's a default value like `add-pr-comment`.

2024-07-24 15:06 UTC, kellervater commented on .github/workflows/preview-env-teardown.yml
> +          message-id: preview-env-status
`message-id` is also not necessary, if you don't plan on having more than one comment you want to update throughout the process. There's a default value like `add-pr-comment`.

2024-07-25 07:39 UTC, kellervater approved these changes

2024-07-25 07:48 UTC, merged