docs(web-modeler): update dependencies for 8.6.0-alpha4
camunda/camunda-docs pull request #4120
Opened 2024-08-07 13:03 UTC by vpellegrino

## Description

Part of https://github.com/camunda/web-modeler/issues/10043

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [x] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-08-07 18:30 UTC, jfriedenstab requested changes

2024-08-07 18:30 UTC, jfriedenstab commented on docs/reference/dependencies.md
> +- [jakarta.transaction:jakarta.transaction-api@2.0.1](https://projects.eclipse.org/projects/ee4j.jta) ([EPL 2.0](http://www.eclipse.org/legal/epl-2.0)) and ([GPL2 w/ CPE](https://www.gnu.org/software
Let's use a single license only:
```suggestion
- [jakarta.servlet:jakarta.servlet-api@6.0.0](https://projects.eclipse.org/projects/ee4j.servlet) ([EPL 2.0](http://www.eclipse.org/legal/epl-2.0))
- [jakarta.transaction:jakarta.transaction-api@2.0.1](https://projects.eclipse.org/projects/ee4j.jta) ([EPL 2.0](http://www.eclipse.org/legal/epl-2.0))
```

2024-08-08 07:13 UTC, vpellegrino commented on docs/reference/dependencies.md
> +- [jakarta.transaction:jakarta.transaction-api@2.0.1](https://projects.eclipse.org/projects/ee4j.jta) ([EPL 2.0](http://www.eclipse.org/legal/epl-2.0)) and ([GPL2 w/ CPE](https://www.gnu.org/software
Good catch! Thanks, @jfriedenstab

2024-08-08 08:21 UTC, jfriedenstab approved these changes

2024-08-08 08:21 UTC, merged