FOOP: UPDATE CONNECTORS
camunda/camunda-docs pull request #4187
Opened 2024-08-22 16:25 UTC by nikku

## Description

Related to https://github.com/camunda/camunda-modeler/pull/4474

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-08-23 13:46 UTC, barmac submitted a review, later dismissed

2024-08-26 07:51 UTC, nikku commented
https://github.com/camunda/camunda-docs/pull/4187/commits/0c69b27f66d65b03556d308ecc098f72775376f0 added to support https://github.com/camunda/camunda-modeler/pull/4479.

2024-08-26 12:46 UTC, barmac commented on docs/components/modeler/desktop-modeler/flags/flags.md
> +  "enable-connector-templates": false
```suggestion
  "disable-connector-templates": true
```

2024-08-26 12:47 UTC, barmac commented on docs/components/modeler/desktop-modeler/use-connectors.md
> +- [Desktop Modeler flags](./flags/flags.md#enable-connector-templates)
```suggestion
- [Desktop Modeler flags](./flags/flags.md#disable-connector-templates)
```

2024-08-26 12:47 UTC, barmac commented on versioned_docs/version-8.5/components/modeler/desktop-modeler/use-connectors.md
> +- [Desktop Modeler flags](./flags/flags.md#enable-connector-templates)
```suggestion
- [Desktop Modeler flags](./flags/flags.md#disable-connector-templates)
```

2024-08-26 12:48 UTC, barmac commented
There are still some places to update with the flag change, but overall it looks good.

2024-08-26 12:55 UTC, nikku commented
My appologies. Not sure how I missed these changes :see_no_evil:

2024-08-26 12:56 UTC, barmac approved these changes

2024-08-27 13:50 UTC, conceptualshark requested changes
I pushed a few changes to clean up the organization/linking on this page, and this seems pretty good to go. 

However, the old `enable` version of the feature flag is still referenced in the [release notes](https://docs.camunda.io/docs/next/reference/release-notes/860/#using-camunda-8-connectors-in-desktop-modeler). I couldn't find any updated copy for this section, and wasn't sure if it should come from Product vs my own edits.

2024-08-27 14:21 UTC, nikku commented
@conceptualshark Cf. https://github.com/camunda/camunda-docs/pull/4187/commits/27cabcdee0e62fbe5cfa1b2246e0c692e8ca9ab4#r1732955161. I'll revert the change of URL and update the release notes according to https://github.com/camunda/camunda-docs/pull/4187#issuecomment-2312705364.

2024-08-27 14:58 UTC, nikku reviewed
@conceptualshark Please see my latest updates

* restoring the link
* re-phrasing the 8.6 release notes section

2024-08-27 16:12 UTC, conceptualshark submitted a review, later dismissed
Thanks for the catch on the link, and the updates! LGTM! 👍

2024-08-27 18:12 UTC, christinaausley commented on docs/reference/release-notes/860.md
> +The Modeler now makes templates for pre-built Camunda 8 connectors available for use in BPMN diagrams. This ensures you can easily connect to a growing list of services and protocols, out of the box.
Regardless of wording, we do need to uppercase Connectors consistently 😄

2024-08-28 09:00 UTC, nikku commented on docs/reference/release-notes/860.md
> +The Modeler now makes templates for pre-built Camunda 8 connectors available for use in BPMN diagrams. This ensures you can easily connect to a growing list of services and protocols, out of the box.
```suggestion
Modeler now offers pre-built templates in BPMN diagrams for Camunda 8 Connectors. This ensures you can easily connect to a growing list of services and protocols, out of the box.
```

2024-08-28 09:01 UTC, nikku commented on docs/reference/release-notes/860.md
> +The Modeler now makes templates for pre-built Camunda 8 connectors available for use in BPMN diagrams. This ensures you can easily connect to a growing list of services and protocols, out of the box.
Applied, thanks.

2024-08-28 14:59 UTC, christinaausley approved these changes

2024-08-28 15:12 UTC, merged