feat(feel): Clarify edge cases in FEEL expressions
camunda/camunda-docs pull request #4222
Opened 2024-08-30 12:36 UTC by saig0

## Description

Extend the FEEL documentation to clarify edge cases, related to the following issues:
- https://github.com/camunda/feel-scala/pull/887
- https://github.com/camunda/feel-scala/issues/801
- https://github.com/camunda/feel-scala/issues/731
- https://github.com/camunda/feel-scala/issues/867  

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-08-30 13:08 UTC, saig0 commented
Changed pages:
- https://preview.docs.camunda.cloud/pr-4222/docs/next/components/modeler/feel/language-guide/feel-unary-tests/
- https://preview.docs.camunda.cloud/pr-4222/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion/#numberfrom
- https://preview.docs.camunda.cloud/pr-4222/docs/next/components/modeler/feel/language-guide/feel-temporal-expressions/#literal
- https://preview.docs.camunda.cloud/pr-4222/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#substringstring-start-position-length

2024-09-05 07:16 UTC, nicpuppa reviewed
Hey @saig0 I left some small wording suggestions please have a look 👀

2024-09-05 07:16 UTC, nicpuppa commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` that is invalid because June has
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` which is invalid because June has
```

2024-09-05 07:16 UTC, nicpuppa commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` that is invalid because
```suggestion
Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` that is invalid because
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on docs/components/modeler/feel/language-guide/feel-temporal-expressions.md
> +`@"2024-06-31"` that is invalid because June has only 30 days.
```suggestion
`@"2024-06-31"` which is invalid because June has only 30 days.
```

2024-09-05 07:16 UTC, nicpuppa commented on docs/components/modeler/feel/language-guide/feel-unary-tests.md
> +When a unary operator is not enough to express the condition, any expression can be used that returns a boolean value,
```suggestion
When a unary operator is not enough to express the condition, any expression that returns a boolean value can be used,
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.2/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` that is invalid because June has
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` which is invalid because June has
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.2/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` that is invalid because
```suggestion
Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.2/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` that is invalid because
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.2/components/modeler/feel/language-guide/feel-temporal-expressions.md
> +`@"2024-06-31"` that is invalid because June has only 30 days.
```suggestion
`@"2024-06-31"` which is invalid because June has only 30 days.
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.2/components/modeler/feel/language-guide/feel-unary-tests.md
> +When a unary operator is not enough to express the condition, any expression can be used that returns a boolean value,
```suggestion
When a unary operator is not enough to express the condition, any expression that returns a boolean value can be used,
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.3/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` that is invalid because June has
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` which is invalid because June has
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.3/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` that is invalid because
```suggestion
Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.3/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` that is invalid because
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-temporal-expressions.md
> +`@"2024-06-31"` that is invalid because June has only 30 days.
```suggestion
`@"2024-06-31"` which is invalid because June has only 30 days.
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.3/components/modeler/feel/language-guide/feel-unary-tests.md
> +When a unary operator is not enough to express the condition, any expression can be used that returns a boolean value,
```suggestion
When a unary operator is not enough to express the condition, any expression that returns a boolean value can be used,
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.4/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` that is invalid because June has
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` which is invalid because June has
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.4/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` that is invalid because
```suggestion
Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.4/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` that is invalid because
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.4/components/modeler/feel/language-guide/feel-temporal-expressions.md
> +`@"2024-06-31"` that is invalid because June has only 30 days.
```suggestion
`@"2024-06-31"` which is invalid because June has only 30 days.
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.4/components/modeler/feel/language-guide/feel-unary-tests.md
> +When a unary operator is not enough to express the condition, any expression can be used that returns a boolean value,
```suggestion
When a unary operator is not enough to express the condition, any expression that returns a boolean value can be used,
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.5/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` that is invalid because June has
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` which is invalid because June has
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.5/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` that is invalid because
```suggestion
Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.5/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` that is invalid because
```suggestion
Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` which is invalid because
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.5/components/modeler/feel/language-guide/feel-temporal-expressions.md
> +`@"2024-06-31"` that is invalid because June has only 30 days.
```suggestion
`@"2024-06-31"` which is invalid because June has only 30 days.
```

2024-09-05 07:16 UTC, nicpuppa commented on versioned_docs/version-8.5/components/modeler/feel/language-guide/feel-unary-tests.md
> +When a unary operator is not enough to express the condition, any expression can be used that returns a boolean value,
```suggestion
When a unary operator is not enough to express the condition, any expression that returns a boolean value can be used,
```

2024-09-05 07:51 UTC, nicpuppa submitted a review, later dismissed
Thanks @saig0 🚀

2024-09-05 07:52 UTC, mesellings commented
@saig0 I will review this for you 👍

2024-09-05 08:05 UTC, mesellings requested changes
Lgtm @saig0 - I've left a few changes/suggestions that need to be applied to the other versions as well, and a single typo, but happy to approve if you accept these?

2024-09-05 08:05 UTC, mesellings commented on docs/components/modeler/feel/language-guide/feel-temporal-expressions.md
>  Adds a value to another value. The operator is defined for the followings types.
```suggestion
Adds a value to another value. The operator is defined for the following types.
```

2024-09-05 08:05 UTC, mesellings commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-string.md
> +Returns a substring of the given value starting at `start position` with the given `length`. If `length` is greater than
```suggestion
Returns a substring of the given value, starting at `start position` with the given `length`. If `length` is greater than
```

2024-09-05 08:05 UTC, mesellings commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31"` which is invalid because June has
```suggestion
Returns `null` if the string is not a valid calendar date. For example, `"2024-06-31"` is invalid because June has
```

2024-09-05 08:05 UTC, mesellings commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the components don't represent a valid calendar date, for example, `2024,6,31` which is invalid because
```suggestion
Returns `null` if the components don't represent a valid calendar date. For example, `2024,6,31` is invalid because
```

2024-09-05 08:05 UTC, mesellings commented on docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion.md
> +Returns `null` if the string is not a valid calendar date, for example, `"2024-06-31T10:00:00"` which is invalid because
```suggestion
Returns `null` if the string is not a valid calendar date. For example, `"2024-06-31T10:00:00"` is invalid because
```

2024-09-05 09:21 UTC, mesellings approved these changes
Lgtm 👍

2024-09-05 09:22 UTC, saig0 commented
@mesellings thank you for your fast feedback and suggestions. :+1:

2024-09-05 11:00 UTC, saig0 commented
@mesellings / @nicpuppa I need another approval. I rebased the branch to `main`.

2024-09-05 11:07 UTC, nicpuppa approved these changes

2024-09-05 11:35 UTC, merged