feat: adding adaptSecurityContxt option to OpenShift alpha docs
camunda/camunda-docs pull request #4246
Opened 2024-09-03 15:59 UTC by hamza-m-masood

## Description

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-09-03 20:55 UTC, conceptualshark commented on docs/self-managed/setup/deploy/openshift/redhat-openshift.md
> +  --set global.compatibility.openshift.adaptSecurityContext=disabled
Should this be `adaptSecurityContext=force` as in the instructions?

2024-09-05 15:36 UTC, conceptualshark submitted a review, later dismissed

2024-09-12 20:51 UTC, aabouzaid requested changes

2024-09-12 20:51 UTC, aabouzaid commented on docs/self-managed/setup/deploy/openshift/redhat-openshift.md
>  export CHART_VERSION="<DESIRED_CHART_VERSION>"
No need for this var anymore.

2024-09-13 11:06 UTC, hamza-m-masood commented on docs/self-managed/setup/deploy/openshift/redhat-openshift.md
>  export CHART_VERSION="<DESIRED_CHART_VERSION>"
Removed

2024-09-13 14:10 UTC, aabouzaid submitted a review, later dismissed

2024-09-13 14:11 UTC, hamza-m-masood commented
@conceptualshark Feel free to merge.

2024-09-17 19:26 UTC, conceptualshark submitted a review, later dismissed

2024-09-17 19:56 UTC, conceptualshark approved these changes

2024-09-17 19:56 UTC, merged