clean up references of cluster auto pause
camunda/camunda-docs pull request #4331
Opened 2024-09-20 16:58 UTC by christinaausley

## Description

Closes https://github.com/camunda/developer-experience/issues/390.

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [x] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [x] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-09-20 17:57 UTC, conceptualshark reviewed
I should have caught this in the last PR; what is the status of autopause as a feature? It looks like it's in the alpha5 release notes, and available in production. Is the limitation captured in these warnings something we should have removed with 8.5 (or in 8.6)? 

Depending on the answer I think we may be able to make the auto-pause warnings a bit clearer.

2024-09-23 16:51 UTC, christinaausley commented
> what is the status of autopause as a feature? It looks like it's in the alpha5 release notes, and available in production. Is the limitation captured in these warnings something we should have removed with 8.5 (or in 8.6)? Depending on the answer I think we may be able to make the auto-pause warnings a bit clearer.

CC @ultraschuppi do you have any comments here?

2024-09-26 11:54 UTC, mesellings commented
@christinaausley I can probably assist here, but might not be able to look at today - I will take a look tomorrow and should be able to clear up any confusion etc 👍

2024-10-03 09:38 UTC, mesellings requested changes
Just a rewording suggestion, but I think we need to remove the auto-pause caution now as it is no longer relevant?

2024-10-03 09:38 UTC, mesellings commented on docs/components/concepts/clusters.md
> +
Shouldn't this caution be deleted as auto-pause is out now?

2024-10-03 09:38 UTC, mesellings commented on docs/components/concepts/clusters.md
> +- When a cluster is paused, not all functionality is limited. For example, you may still execute BPMN timers and BPMN message catch events.
```suggestion
- Paused clusters still retain some functionality. For example, you can still execute BPMN timers and BPMN message catch events.
```
Rewording suggestion

2024-10-03 09:38 UTC, mesellings commented on versioned_docs/version-8.5/components/concepts/clusters.md
> +
See previous comment - remove?

2024-10-03 09:38 UTC, mesellings commented on versioned_docs/version-8.5/components/concepts/clusters.md
> +- When a cluster is paused, not all functionality is limited. For example, you may still execute BPMN timers and BPMN message catch events.
See previous rewording suggestion

2024-10-03 17:20 UTC, christinaausley commented
@mesellings Given the changes over the past few weeks with auto-pause, I'm just going to close this out 👍 Thank you for your review!

2024-10-03 17:20 UTC, closed without merging

2024-10-04 07:43 UTC, mesellings commented
Sounds good thank you! 👍