docs(play): mention feature limitations in Play
camunda/camunda-docs pull request #4339
Opened 2024-09-24 06:41 UTC by huygur

## Description

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [ ] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [ ] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-09-24 07:24 UTC, HanselIdes approved these changes
LGTM - a few minor suggestions. You do not need to re-request a review

2024-09-24 07:24 UTC, HanselIdes commented on docs/components/modeler/web-modeler/play-your-process.md
> +- Play doesn't support call activities with feel expressions
```suggestion
- Play doesn't support call activities with FEEL expressions
```
a link here may be helpful if this is the first mention of FEEL in the page- https://docs.camunda.io/docs/components/modeler/feel/what-is-feel/

2024-09-24 07:24 UTC, HanselIdes commented on docs/components/modeler/web-modeler/play-your-process.md
> +- While you can still interact with your process instance in Play—such as completing jobs or publishing messages—you may be unable to resolve incidents if they occur beyond the 100th flow node instan
```suggestion
- While you can still interact with your process instance in Play, such as completing jobs or publishing messages. you may be unable to resolve incidents if they occur beyond the 100th flow node instance, as Play does not track them. In this case, incident resolution can be managed in Operate.
```

2024-09-24 14:57 UTC, conceptualshark submitted a review, later dismissed

2024-09-25 05:45 UTC, huygur commented
@HanselIdes @conceptualshark I need an approval again to merge, as I pushed a commit to fix a broken link 😅

2024-09-25 07:17 UTC, yT0n1 requested changes
Lgtm, but we should add a general limitation for things defined through feel

2024-09-25 07:17 UTC, yT0n1 commented on docs/components/modeler/web-modeler/play-your-process.md
> +- Play doesn't support call activities with [FEEL expressions](/components/modeler/feel/what-is-feel.md).
Maybe we can generalize this a bit more, but I don't know what the proper wording would be. Or maybe we just list all the items: 
Play does not support Job Types defined through feel expressions, Message correlation keys defined by feel expressions, called process definitions defined by Feel expressions. Maybe I forgot something 😅

2024-09-25 07:29 UTC, yT0n1 approved these changes
Thanks!

2024-09-25 07:45 UTC, merged