adjust disk-size to sum of zeebe and es
camunda/camunda-docs pull request #4651
Opened 2024-11-25 12:55 UTC by hisImminence

## Description

/closes https://github.com/camunda/doc-hospital/issues/24

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [x] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [x] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-11-25 12:58 UTC, npepinpe approved these changes

2024-11-25 14:21 UTC, jonathanlukas approved these changes

2024-11-26 11:24 UTC, jonathanlukas requested changes

2024-11-26 11:24 UTC, jonathanlukas commented on docs/components/best-practices/architecture/sizing-your-environment.md
> +| Approximate resources provisioned **\*\*\*\***                                      | 11 vCPU, 22 GB memory, 192 GB disk. | 22 vCPU, 384 GB memory, 128 GB disk. | 33 vCPU, 66 GB mem, 576 GB disk. |
I think the x2 column would not require 384 gb ram, instead the disk space needs to be adjusted:
```suggestion
| Approximate resources provisioned **\*\*\*\***                                      | 11 vCPU, 22 GB memory, 192 GB disk. | 22 vCPU, 44 GB memory, 384 GB disk. | 33 vCPU, 66 GB mem, 576 GB disk. | 44 vCPU, 88 GB mem, 768 GB disk. |
```

2024-11-26 11:24 UTC, jonathanlukas commented on versioned_docs/version-8.6/components/best-practices/architecture/sizing-your-environment.md
> +| Approximate resources provisioned **\*\*\*\***                                      | 11 vCPU, 22 GB memory, 192 GB disk. | 22 vCPU, 384 GB memory, 128 GB disk. | 33 vCPU, 66 GB mem, 576 GB disk. |
Same goes for the versioned docs

```suggestion
| Approximate resources provisioned **\*\*\*\***                                      | 11 vCPU, 22 GB memory, 192 GB disk. | 22 vCPU, 44 GB memory, 384 GB disk. | 33 vCPU, 66 GB mem, 576 GB disk. | 44 vCPU, 88 GB mem, 768 GB disk. |
```

2024-11-27 00:05 UTC, hisImminence commented
Great catch! Thanks @jonathanlukas 🤝

2024-11-27 04:18 UTC, jonathanlukas approved these changes

2024-11-27 08:24 UTC, mesellings approved these changes
Lgtm 👍

2024-11-27 12:11 UTC, merged

2024-11-27 12:15 UTC, mesellings commented
Published in the latest docs release today 👍

2024-11-28 15:17 UTC, hisImminence commented
Thanks @mesellings!