Helm Chart Production Guide (8.8)
camunda/camunda-docs pull request #4703
Opened 2024-12-03 17:29 UTC by hamza-m-masood

## Description

closes: https://github.com/camunda/distribution/issues/344
## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [x] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [ ] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [ ] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [x] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [x] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-12-12 10:24 UTC, hamza-m-masood commented
@conceptualshark, I wanted to add a link to the OpenSearch IRSA guide, but I am having a problem with the docs. I opened an issue here: https://github.com/camunda/camunda-docs/issues/4754

2025-01-06 14:04 UTC, theburi reviewed
I did a first pass, it looks good.
I added some notes when we should rephrase text for better readability ad clarity.

2025-01-06 14:04 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +- It is best to only pull from a private registry such as [Amazon ECR](https://aws.amazon.com/ecr/) and not pull directly from Docker Hub. This is because it will increase the control you have over t
It is recommended to pull images exclusively from a private registry, such as [Amazon ECR](https://aws.amazon.com/ecr/), rather than directly from Docker Hub. Doing so enhances control over the images, avoids rate limits, and improves performance and reliability. Additionally, you can configure your cluster to pull images only from trusted registries. Tools like [Open Policy Agent](https://blog.openpolicyagent.org/securing-the-kubernetes-api-with-open-policy-agent-ce93af0552c3#3c6e) can be used to enforce this restriction.

2025-01-06 14:04 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to enable Prometheus on the Camunda Helm Chart. This can be added to your `production-values.yaml`:
It is possible to enable integration with Prometheus, a popular monitoring solution, in the Camunda Helm Chart. This can be configured by adding values below to your `production-values.yaml`:

2025-01-06 14:04 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to enable audit logging for Camunda components to track user actions, especially for sensitive data or configuration changes. Here is an example configuration to change the log level
Can we add an example to changs logging to all components? It is often asked for

2025-01-06 14:04 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like to run benchmarks on the platform then please refer to our [community project](https://github.com/camunda-community-hub/camunda-8-benchmark)
Can we consider next steps or call for Action?

What would be the next steps after this guide is completed?

2025-01-07 18:24 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +This guide provides a simplified and streamlined 3-pod deployment architecture for core Camunda 8 applications using the Camunda Helm Chart. This setup minimizes complexity while offering a reliable
changed

2025-01-07 18:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +  - **Amazon OpenSearch**: For indexing and analytics.
I'm not exactly sure what you would like me include/exclude here

2025-01-07 18:29 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Prerequisites
What guides exactly?

2025-01-07 18:44 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +  - OpenSearch (for indexing and analytics)
nice catch thanks

2025-01-07 18:46 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +2. A TLS certificate created from your domain. The certificate must be an X.509 certificate, issued by a trusted Certificate Authority. Also, the certificate must include the correct domain names (Co
What do you mean?

2025-01-07 18:46 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +2. A TLS certificate created from your domain. The certificate must be an X.509 certificate, issued by a trusted Certificate Authority. Also, the certificate must include the correct domain names (Co
Ah I see what you mean.

2025-01-07 18:50 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +        redirectUrl: "https://core.camunda.example.com"
@jessesimpson36 would you be able to review the values.yaml I provided for OIDC?

2025-01-07 18:51 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +In our scenario the Core component, and the Optimize importer communicates with a singular Amazon OpenSearch instance. On the other hand, the identity and web-modeler component are connected to seper
Even for external Identity? Would you have a slack thread or some document I could see that states this?

2025-01-07 19:18 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +In our scenario the Core component, and the Optimize importer communicates with a singular Amazon OpenSearch instance. On the other hand, the identity and web-modeler component are connected to seper
@theburi please look at this response from the identity team on a question I sent previously:
https://camunda.slack.com/archives/CRQAL5A1M/p1730286741885819?thread_ts=1730285348.529049&cid=CRQAL5A1M

2025-01-07 19:19 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +An index lifecycle management (ILM) policy in OpenSearch is crucial for efficient management and operation of large-scale search and analytics workloads. ILM policies provide a framework for automati
What exactly would you like to mention?

2025-01-07 19:23 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Application-Specific Configurations
I will rename it to Camunda Core configuration

2025-01-07 19:23 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Installation and Configuration
This section is supposed to be about installation configuration of the helm chart in general. The next section is about configuring the camunda components specifically.

2025-01-07 19:25 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Installation and Configuration
I hope it is clearer now with the other title changed to Camunda Core configuration

2025-01-08 12:19 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +The `core.partitionCount` does not support dynamic scaling. You will not be able to modify it on future upgrades.
This is already mentioned in the prerequisite section

2025-01-08 12:24 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Check the resource (CPU and memory) limits set and make sure they are reasonable. For example, the resource limits can be changed for the core component by modifying the following values:
Would you like me to mention the sizing guide again here when it is already mentioned in the prerequisite?

2025-01-08 12:32 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Secrets should be created prior to installing the helm chart so they can be referenced as existing secrets when installing the helm chart.
In this scenario, I chose to auto-generate the secrets. I did not mention that in the above sentence. Nice catch.

2025-01-08 17:19 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +  Please refer to the [Kuberentes documentation](https://kubernetes.io/docs/concepts/configuration/secret/) on how to create a secret.
same as this comment I mentioned here: https://github.com/camunda/camunda-docs/pull/4703#discussion_r1907114748

2025-01-08 17:31 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- It is recommended to set a memory and resource quota for your namespace. Please refer to the [Kubernetes documenation](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-mem
I took namespace configuration out of prerequisites

2025-01-08 17:33 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to have a pod security standard that is suitable to the security constraints you might have. This is possible through modifying the Pod Security Admission. Please refer to the [Kuber
You highlighted two points here. Which of the two points is hard to read for you?
The first point highlighted is clear. Even the second point is clear to me. What would be hard to read specifically in the second point?

2025-01-09 11:54 UTC, hisImminence requested changes
left also some comments

2025-01-09 11:57 UTC, hisImminence requested changes

2025-01-09 11:57 UTC, hisImminence commented on docs/self-managed/operational-guides/assets/smarch.jpg
Considering the DRY principle, should we just add a link to the architecture section and add to the prerequisits something like: Familiarize yourself with the HC architecture (link to https://docs.camunda.io/docs/self-managed/about-self-managed/#architecture)

2025-01-09 12:14 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to enable audit logging for Camunda components to track user actions, especially for sensitive data or configuration changes. Here is an example configuration to change the log level
An example like that could get out of date very quickly. I think it is better to instead guide the customer to the respective application components to view how to modify the log levels. This will reduce repetition in our docs.
What do you think @theburi ?

2025-01-09 12:16 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like to run benchmarks on the platform then please refer to our [community project](https://github.com/camunda-community-hub/camunda-8-benchmark)
I pretty much have mentioned all of these points already. I guess I can rename "Other Concepts to take note of" to "next steps"

that would make things clearer

2025-01-09 12:17 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +  Camunda Platform Core Applications: Zeebe, Tasklist, Operate
Good point. The diagram still needs to be updated. I will change the wording underneath.

2025-01-09 12:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +The goal of this guide is to give you a **scenario-based, production focused, step-by-step guide** for setting up the Camunda Helm Chart. By following this guide, you will be familiar with all of the
Good point. I will add that we use AWS as a reference.

2025-01-09 12:44 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- **NGINX Ingress Controller**: Ensure the NGINX ingress controller is set up in the cluster.
dangerous territory. I don't know whether the helm chart was ever adjusted but afaik it's relying on the defaults of the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) controller.

Just saying `NGINX Ingress Controller` will result in people wanting and using the [NGINX Ingress Controller](https://docs.nginx.com/nginx-ingress-controller/) by F5.

If people google for it 1 by 1, they will end up based on the naming at F5.

I'd consider the naming + consider a direct link to the project you mean.

2025-01-09 12:45 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- **NGINX Ingress Controller**: Ensure the NGINX ingress controller is set up in the cluster.
we have had incidents in the past as people were using the F5 nginx ingress controller as it doesn't work out of the box with the helm chart, especially around gRPC.

2025-01-09 12:47 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Make sure secrets are not auto-generated on upgrade.
@hisImminence, thanks. This is the only section that is incomplete. I still need to have a session with @aabouzaid about other items that need to be added here. You wrote a good paragraph. I will make sure to use it. 🙌

2025-01-09 12:49 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- **Helm**: Helm CLI installed
I'm wondering whether it makes sense here to link to somewhere where we state what versions we support or like minimum (> x).
Helm had issues in the past and people will use the guide and expect similar results and could debug differences to their own environments if they run into problems.

2025-01-09 12:51 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- **s3 Bucket** - This will be used to store backups of the Camunda cluster. This s3 bucket must be configured with OpenSearch to take backups.
afaik S3 is a proper noun

2025-01-09 12:52 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- **AWS OpenSearch Snapshot Repository** - This will be a place to store the backups of the Camunda cluster. This repository must be configured with OpenSearch to take backups.
just looking for `snapshot` in the doc, I guess it's not further covered.
Could we link to something upstream from AWS on the topic?

2025-01-09 12:55 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- Ingress Controller (e.g., Nginx)
here I'd again consider spelling out the one you mean to avoid confusion.
While I get that any Ingress controller would do the trick, the defaults, that afaik the guide is also relying on, is `ingress-nginx`.
Any other controller may require extra input from the user (not covered by Camunda)

2025-01-09 15:09 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +    --values production-values.yaml
I'd recommend mentioning probably both of the following

```
helm repo add camunda https://helm.camunda.io
```

```
helm repo update
```

depends a bit.
If it's a new user, they may not have added the helm chart repo yet.
If it's an existing user, they may not have updated it in a while.

2025-01-09 15:11 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +3. A TLS secret created from your TLS certificate. In our example, we will use a secret called `camunda-platform`. Please refer to the [kuberntes documentation](https://kubernetes.io/docs/concepts/co
```suggestion
3. A TLS secret created from your TLS certificate. In our example, we will use a secret called `camunda-platform`. Please refer to the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets) on how to make a TLS secret.
```

2025-01-09 15:13 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +For more information on the Ingress setup, please refer to our [ingress setup guide](/self-managed/setup/guides/ingress-setup.md)
not sure whether `ingress` is capital or not but would suggest to align for a single written way, maybe @conceptualshark can give an input.

I've seen various ways of `ingress` and `Ingress` throughout the document. (Capital I or not).

2025-01-09 15:20 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +      type: "MICROSOFT"
I'm very confused. We're saying we're using `AWS Simple Active Directory,` but then everything links to Microsoft.

I don't think AWS would link to Microsoft but happy to learn more about it!
Coming to the next point, any guidance or help on where you got the values from?
Can we guide the user better to where they would get the `00000-000....` etc. etc. from? E.g. upstream AWS docs follow X, you receive Y.

- [ ] Why Microsoft if we say AWS?
- [ ] Can we guide the user better to where they should retrieve the values from?

2025-01-09 15:22 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +The next stage of the production setup is configuring databases. To make it easy for testing, the Camunda Helm Chart provides external, dependency Helm Charts for Databases such as Bitnami Elasticsea
Optional suggestion to link to e.g. elasticsearch and progresql bitnami charts via artifacthub.io
- https://artifacthub.io/packages/helm/bitnami/postgresql
- https://artifacthub.io/packages/helm/bitnami/elasticsearch

2025-01-09 15:26 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +## Prerequisites
The following could be good starting points:

- https://docs.camunda.io/docs/self-managed/setup/deploy/amazon/amazon-eks/eks-terraform/
- https://docs.camunda.io/docs/self-managed/setup/deploy/amazon/amazon-eks/eks-helm/

You have a lot of `assume you have x ready`; those could be good linkages to what we have to guide the user.
Atm, I assume your postgres etc. is ready.
Since your production readiness guide is based on AWS, you could reference what exists to create more value for the user.

2025-01-09 15:31 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- [Running Web Modeler on Amazon Aurora PostgreSQL](/self-managed/modeler/web-modeler/configuration/database.md/#running-web-modeler-on-amazon-aurora-postgresql)
This could be considered to be moved to line 165 where it mentions `It is assumed that you already have one Amazon OpenSearch instance and two Amazon Aurora PostgreSQL instances setup and ready to go with a username, password, and URL.`

That's also what I mean in the comment [here](https://github.com/camunda/camunda-docs/pull/4703/files#r1909014785).

Probably needs to be rephrased a bit along the lines of `It is expected that you already have one Amazon OpenSearch instance and two Amazon Aurora PostgreSQL instances configured and ready to use, complete with a username, password, and URL. If not, refer to the following guides to help you get started before you continue`.

2025-01-09 15:32 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +It is assumed that you already have one Amazon OpenSearch instance and two Amazon Aurora PostgreSQL instances setup and ready to go with a username, password, and URL.
why are we proposing two Postgresql instances?
What's the advantage to a single instance with two individual databases inside?

2025-01-09 15:35 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +  Camunda Platform Orchestration Core Components: Zeebe, Tasklist, Operate, Optimize
looking at he above picture, are we missing Console, Identity, and Web-Modeler here?

2025-01-09 15:37 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +At this point you are able to connect to your platform through HTTPS, correctly authenticate users using AWS Simple Active Directory, and have connected to external databases such as Amazon OpenSearc
I'd suggest rephrasing it to in a hypothetical sense since afaik the user shouldn't be running helm upgrade every time, right?

`... you would be able ...`

2025-01-09 15:38 UTC, Langleu requested changes
Leaving my review so far already.
I've only come halfway so far and would continue tomorrow to read through the rest.

2025-01-09 16:35 UTC, jessesimpson36 commented on docs/self-managed/operational-guides/production-guide.md
> +        redirectUrl: "https://core.camunda.example.com"
https://docs.camunda.io/docs/next/self-managed/setup/guides/connect-to-an-oidc-provider/#configuration

this page already has an example for setting up oidc ,  perhaps we should link it instead?

2025-01-10 09:00 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +It is assumed that you already have one Amazon OpenSearch instance and two Amazon Aurora PostgreSQL instances setup and ready to go with a username, password, and URL.
In https://docs.camunda.io/docs/next/self-managed/setup/deploy/amazon/amazon-eks/eks-terraform/#configure-the-database-and-associated-access we use one Postgres instance for example and as mentioned just add databases within the Postgres instance, so data is still separated from each other, also each app their own user / pw etc.

If there's a good reason on why one should go with 2 separate instances, we should consider aligning those.

2025-01-10 10:26 UTC, Langleu requested changes
Second part and overall impressions:

- I'm not entirely sure about the focus on AWS.  
   - You don't seem to leverage much that's specifically AWS-related, apart from possibly the Identity Provider topic. This could just be kept general, or as Jesse suggested, you could simply reference the page you already have.  
   - Beyond that, the content could easily be generalized and doesn't necessarily need AWS-specific details. AWS services could be an example, especially with the guides we have.

The reason I bring this up is that it raises a question for customers: what is the value of this compared to the AWS-specific guides we already provide?

The AWS guide provides a clear, step-by-step approach that leads to a working solution. In contrast, this page, at least for me, seems to aim for a similar outcome but doesn't fully achieve it, as the aim should be to generalise it actually which is countering a working result.  

What I mean is that this page might benefit from focusing more on Helm Chart production readiness configuration and maybe Camunda itself. It could dive deeper into the reasoning behind the recommendations, rather than assuming the audience will accept them without question. Explain why specific suggestions are made, what they achieve, and how they relate to the context of the Helm Chart. Essentially, ask: Why is this recommended? What purpose does it serve? Providing this level of detail would enhance the clarity and usefulness of the guide.  

E.g. for the Databases, is there anything else we recommend as production or is there any default already in place e.g. some environment variables that optimize the connection. 

Index retention for example, you show how to configure it but if I'm thinking production, then why is it recommended what does it mean, how do I possible have to adjusted for my own use case and why.

Similar thought about Scaling and performance.

Ultimately, that's just my pov and feel free to adjust things the way you see as you're owning the topic.

The TL:DR is:
- Ask yourself why on each recommendation?
- Don't assume customers will take it at face value.
- What's the big difference to the AWS guides and unique selling point?
- Keep it general (removing AWS focus if possible)

I'm on FTO next week, so feel free to dismiss my review worst case.

2025-01-10 10:26 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- Open Policy Agent can also be used to [whitelist for ingress hostnames](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#4-define-a-policy-and-load-it-into-opa-via-kubernetes).
maybe do a single point of Open Policy Agent combining this and the previous trusted sources one as sub points?

-  .... recommended to use private registry ...
- ... Open Policy Agent ...
    - trusted registry topic
    - whitelist ingress topic

For the whitelist ingress topic, again why should it be done, what's the advantage as to why we recommend it.

2025-01-10 10:26 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +Make sure secrets are not auto-generated on upgrade.
I can't link my comment from above, but that's exactly what I meant earlier when the auto-generating of the secrets was created. If we already say in the next steps that you should be careful with auto-generated secrets, then it's not a production recommendation.

2025-01-10 10:40 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide.md
> +- Check node affinity and tolerations. Please refer to the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to modify the node affinity and to
Again, the why and maybe an example of how one should taint, node, zone, or something, and what we recommend as criteria.

2025-01-10 13:18 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +## Prerequisites
thanks Lars, this is exactly what I was thinking about.

2025-01-10 13:19 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +- **Helm**: Helm CLI installed
We have a page where we define versions and keep it up to date. Can we maintain these versions in all places?

2025-01-10 13:24 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +- **s3 Bucket** - This will be used to store backups of the Camunda cluster. This s3 bucket must be configured with OpenSearch to take backups.
Can we define AWS S3 Bucket as a proper product name

2025-01-10 13:26 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +Within the `management` namespace, we will install Identity, Console, and all the Web Modeler components. Within the `orchestration` namespace, we will install the Camunda Orchestration Core componen
The new term we use is 'Web Modeler and Console.' For the purpose of this guide now, let's use a namespace called 'management' but refer to it as a namespace for Web Modeler and Console.

2025-01-10 13:29 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +The Camunda Helm Chart can be installed using the following command:
Let's be careful with what we mean step-by-step.
Since we are using IaC principles, we have a state of production configuration that users apply to cluster at once and we have a breakdown of each element.
The step-by-step is higher level flow, where users analyse requirements, collect prerequisites, create configuration and apply.

2025-01-10 13:29 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +    --values production-values.yaml
+1

2025-01-10 14:00 UTC, bkenez commented on docs/self-managed/operational-guides/production-guide.md
> +The next stage of the production setup is configuring databases. To make it easy for testing, the Camunda Helm Chart provides external, dependency Helm Charts for Databases such as Bitnami Elasticsea
```suggestion
The next stage of the production setup is configuring databases. To make it easy for testing, the Camunda Helm Chart provides external dependency Helm Charts for Databases such as the Bitnami Elasticsearch Helm Chart and the Bitnami PostgresQL Helm Chart. Within a production setting, these dependency charts should be disabled, and production databases should be used instead. For example, instead of the Bitnami Elasticsearch dependency chart, we will use Amazon OpenSearch, and instead of the Bitnami PostgreSQL dependency chart, we will use Amazon Aurora PostgreSQL.
```
Minor grammar correction to use the definitive article for better flow and consistency within the paragraph.

2025-01-10 14:09 UTC, bkenez commented on docs/self-managed/operational-guides/production-guide.md
> +You should only enable the auto-mounting of a service account token when the application explicitly needs access to the Kubernetes API server or you have created a service account with the exact perm
```suggestion
You should only enable the auto-mounting of a service account token when the application explicitly needs access to the Kubernetes API server, or you have created a service account with the exact permissions required for the application and bound it to the pod.
```
Missing comma

2025-01-10 15:38 UTC, bkenez commented on docs/self-managed/operational-guides/production-guide.md
> +# make sure to the values.yaml in a multinamespace setting and configure console likewise
This comment is unclear to me.
I think there's a missing verb after "make sure to" also, multi-namespace should be hyphenated.

2025-01-10 16:43 UTC, bkenez commented
With regards to the document as a whole:
I do think that this would be very useful overall. However, my overall takeaway is that for a production guide, there should be less focus on a specific example installation, but rather should delve further into when and mainly why certain options should or should not be used - like Lars had said above, looking at it from a customer perspective I would want to see reasonings behind why something is recommended so I could deepen my understanding about the deployment as a whole, and if I were to choose not to use recommendations then I would also like to be aware of the consequences of doing so.

That said, definitely nice work; I could only really offer some grammar corrections. 👍

2025-01-10 19:57 UTC, hisImminence commented on docs/self-managed/operational-guides/production-guide.md
> +The Camunda Helm Chart can be installed using the following command:
Okay, if thats the case then I am fine with it!

2025-01-20 01:52 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Prerequisites
Thanks. I referenced some guides in the prerequisite section. If I am still missing some please feel free to ping me and let me know.

2025-01-20 01:54 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +        redirectUrl: "https://core.camunda.example.com"
Sure, that's fine with me. I hope the guide does not feel incomplete without the values.yaml for OIDC.

2025-01-20 06:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +The `core.partitionCount` does not support dynamic scaling. You will not be able to modify it on future upgrades.
I reworded the resource planning section as per your suggestion @hisImminence.
I also added the "yet" in the `core.partitionCount`
Thanks.

2025-01-20 06:29 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like to run benchmarks on the platform then please refer to our [community project](https://github.com/camunda-community-hub/camunda-8-benchmark)
I will resolve this for now. Since no comments have been given yet. If there is still an issue with this section, please ping me here.

2025-01-20 06:32 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like some more guidance relating to authentication, then please refer to the following guides:
Aaah yes, I was meant to find more guides to add here but was not able to find much else. Thanks for bringing this to my attention again.

2025-01-20 06:52 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +      issuer: "https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0"
I discussed this with @aabouzaid at the time of creating this values.yaml
We thought it best to keep this format because it is the same format as the actual data you would get from Azure. For example 
`00000000-0000-0000-0000-000000000000` equates to `37a5ef7f-4d4e-40c1-acf2-1bdd07613163`

2025-01-20 07:07 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Reliability Best Practices
Good point. I can remove it.

2025-01-20 07:09 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +prometheusServiceMonitor:
Ah, my mistake. Thanks

2025-01-20 07:13 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +    - name: "OPTIMIZE_LOG_LEVEL"
I just gave one example for optimize. I did not give examples for other core applications like zeebe for example, because it would just be more configs to maintain. 

@hisImminence would you like me to add configuring log levels for all the apps? I don't think it is of much value to the customer here in terms of a production setting. They can just refer to the respective application configuration docs to find out.

2025-01-20 07:22 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +The next recommended step is to setup a multi-namespace deployment. A [guide](/self-managed/setup/guides/multi-namespace-deployment.md) for this is already available. This is the most recommended app
I would still like to mention that this is the next step. It gives more of a flow to the article. But I reworded the specific sentence as per your suggestion.

2025-01-20 07:30 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- **NGINX Ingress Controller**: Ensure the NGINX ingress controller is set up in the cluster.
naming changed and link provided. Thanks.

2025-01-20 07:35 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- **s3 Bucket** - This will be used to store backups of the Camunda cluster. This s3 bucket must be configured with OpenSearch to take backups.
@theburi from what I see the proper product name is `Amazon S3`
I will change it. Thanks.

2025-01-20 10:44 UTC, hisImminence commented on docs/self-managed/operational-guides/production-guide.md
> +      issuer: "https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000/v2.0"
ok, we also did not get other feedback ;) then fine to keep it for now!

2025-01-20 12:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- **AWS OpenSearch Snapshot Repository** - This will be a place to store the backups of the Camunda cluster. This repository must be configured with OpenSearch to take backups.
I will reference this document: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshot-registerdirectory.html

2025-01-20 12:32 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Ingress Controller (e.g., Nginx)
I will probably remove this section in favor of @hisImminence's comment here: https://github.com/camunda/camunda-docs/pull/4703#discussion_r1908657029

2025-01-20 12:46 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Within the `management` namespace, we will install Identity, Console, and all the Web Modeler components. Within the `orchestration` namespace, we will install the Camunda Orchestration Core componen
I kept the naming the same and referred to the line that @Langleu provided. Thanks.

2025-01-20 12:51 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +    --values production-values.yaml
added the commands, thanks

2025-01-20 13:18 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +For more information on the Ingress setup, please refer to our [ingress setup guide](/self-managed/setup/guides/ingress-setup.md)
Thanks. I made capitalized to `Ingress`
@conceptualshark if that is not appropriate then feel free to change it in your review

2025-01-20 13:36 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Prerequisites
That's a good suggestion. I added links to as many points as I could

2025-01-20 14:08 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +      type: "MICROSOFT"
AWS Simple AD is just a managed instance of Microsoft AD on AWS.

2025-01-20 14:11 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +      type: "MICROSOFT"
With regards to more guidance, I am hoping the customer clicks on the [OIDC guide](https://docs.camunda.io/docs/next/self-managed/setup/guides/connect-to-an-oidc-provider/#configuration) directly below the values.yaml

2025-01-20 14:15 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +      type: "MICROSOFT"
The reason why I chose AWS Simple AD and not Azure entra was because I wanted to have everything on the same cloud provider. It doesn't make much sense to have  two cloud providers since nobody would really do that in an actually use-case.

2025-01-20 14:26 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- [Running Web Modeler on Amazon Aurora PostgreSQL](/self-managed/modeler/web-modeler/configuration/database.md/#running-web-modeler-on-amazon-aurora-postgresql)
I already mentioned the guides in the prerequisites section. I can just say to refer to the guides there.
Thanks for rephrasing it.

2025-01-20 14:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +It is assumed that you already have one Amazon OpenSearch instance and two Amazon Aurora PostgreSQL instances setup and ready to go with a username, password, and URL.
That's a good point! This is why I wanted a review from infraex team to get feedback like this. Thanks!

2025-01-20 14:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +It is assumed that you already have one Amazon OpenSearch instance and two Amazon Aurora PostgreSQL instances setup and ready to go with a username, password, and URL.
I will mention only one aws aurora psql instance instaed

2025-01-21 21:56 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +  Camunda Platform Orchestration Core Components: Zeebe, Tasklist, Operate, Optimize
I decided to remove the section under the diagram because it repeats what is already clearly outlined in the diagram and causes confusion. Thanks.

2025-01-21 22:05 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Version Management: Stay on a stable Camunda and Kubernetes version. Follow Camunda’s release notes for security patches or critical updates. A list of our supported versions Camunda Helm Charts ca
I will remove the version matrix for now. 
@theburi , @conceptualshark please let me know what you think of the above.

2025-01-21 22:09 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Secrets should be created prior to installing the Helm Chart so they can be referenced as existing secrets when installing the Helm Chart. In this scenario we are going to auto-generate the secrets
@aabouzaid What do you think? 🤔 
I don't see a problem in generating secrets within a production setting if it is a first install.

2025-01-21 23:03 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- It is recommended to set a memory and resource quota for your namespace. Please refer to the [Kubernetes documenation](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-mem
Namespace-Level Quotas apply limits to all workloads within a namespace. It ensures aggregate resource consumption by all pods in the namespace.

Th combined resource usage of all the pods could exceed the desired resource limits of the customer. 

I can add this in with the paragraph, so it is clear. Thanks.
Please ping me here if it is still not clear.

2025-01-21 23:25 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +```
Aah yeah, I see how this can be confusing. Thanks. I just listed out the default pod and container security contexts. It would make more sense for me to mention that it is the default and then direct the customer to the official k8s documentation if they want to add anything else. 

I hope this change will clear any confusion

2025-01-21 23:52 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Secrets should be created prior to installing the Helm Chart so they can be referenced as existing secrets when installing the Helm Chart. In this scenario we are going to auto-generate the secrets
> why isn't it the default anymore in the helm chart?
I think this is so customers don't accidentally enable it on upgrade. It should only be enabled on install.

2025-01-22 00:16 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Open Policy Agent can also be used to [whitelist for ingress hostnames](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#4-define-a-policy-and-load-it-into-opa-via-kubernetes).
> For the whitelist ingress topic, again why should it be done, what's the advantage as to why we recommend it.

It's just a recommendation. I added it because if I was setting up for production, I would want this feature. The reason I recommended it was obviously for enhancing security, but also for error reduction. You reduce the likelihood of misconfigurations related to the hostname.

2025-01-22 00:17 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Open Policy Agent can also be used to [whitelist for ingress hostnames](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#4-define-a-policy-and-load-it-into-opa-via-kubernetes).
I will create a single point for Open Policy Agent. Thanks.

2025-01-22 00:20 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Open Policy Agent can also be used to [whitelist for ingress hostnames](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/#4-define-a-policy-and-load-it-into-opa-via-kubernetes).
I hope this is clear. Feel free to unresolved and ping me if you would like to discuss this further.

2025-01-22 00:30 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Check node affinity and tolerations. Please refer to the [Kubernetes documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to modify the node affinity and to
I included an example of the default setup. Thanks.

2025-01-22 00:34 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +# make sure to the values.yaml in a multinamespace setting and configure console likewise
Ah sorry, I will fix it thanks.

2025-01-22 00:35 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +# make sure to the values.yaml in a multinamespace setting and configure console likewise
Honestly, this is just a note for myself to make sure the values.yaml is working 😄

2025-01-22 04:01 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Check the resource (CPU and memory) limits set and make sure they are reasonable. For example, the resource limits can be changed for the core component by modifying the following values:
I will resolve this point since I have already mentioned the sizing guide above. Feel free to reopen.

2025-01-22 04:03 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to have a pod security standard that is suitable to the security constraints you might have. This is possible through modifying the Pod Security Admission. Please refer to the [Kuber
I will resolve this since the points are clear to me. Feel free to reopen.

2025-01-22 04:22 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/assets/smarch.jpg
Resolving this comment since this point is already mentioned in another comment:
https://github.com/camunda/camunda-docs/pull/4703#discussion_r1907992715

2025-01-22 04:23 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Ingress Controller (e.g., Nginx)
I decided to remove the section under the diagram

2025-01-22 04:36 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- Secrets should be created prior to installing the Helm Chart so they can be referenced as existing secrets when installing the Helm Chart. In this scenario we are going to auto-generate the secrets
Closing this conversation since this point is mentioned in another comment: https://github.com/camunda/camunda-docs/pull/4703#discussion_r1908044536

2025-01-22 05:14 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +```
I added in how to add extraVolumeMounts because it was suggested by @theburi

2025-01-22 05:15 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +```
It makes sense to mention that Helm Charts have PVCs by default and then mention this added usecase

2025-01-22 12:46 UTC, jessesimpson36 commented on docs/self-managed/operational-guides/production-guide.md
> +        redirectUrl: "https://core.camunda.example.com"
You're right, it would defeat the purpose of this guide if we just linked it.

2025-01-22 12:47 UTC, jessesimpson36 commented on docs/self-managed/operational-guides/production-guide.md
> +        redirectUrl: "https://core.camunda.example.com"
Which I think means we're back to validating the final configuration. I can look at that some time.

2025-01-22 15:10 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +        redirectUrl: "https://core.camunda.example.com"
We should treat the production config as an enabled configuration. We could provide one concrete configuration but mention that for a more detailed look to read the OIDC guide.

2025-01-22 15:12 UTC, theburi commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to enable audit logging for Camunda components to track user actions, especially for sensitive data or configuration changes. Here is an example configuration to change the log level
Ok. Let's leave it as it is. I think the Unified configuration project will address this in the future, and we don't have to worry about this.

2025-01-22 18:24 UTC, conceptualshark reviewed
Left one comment, I believe the other area I'm tagged in has been addressed - is this approaching readiness for a tech writer review? Happy to jump in whenever the technical information is ready to go.

2025-01-22 18:24 UTC, conceptualshark commented on docs/self-managed/operational-guides/production-guide.md
> +The `existingSecret` can be used to specify an existing Kubernetes secret with the password.
In this case, I think it's fine to repeat the line in each section. This way, if anyone navigates to only the section they need without reading the other, they can have that information available.

2025-01-22 18:38 UTC, conceptualshark commented on docs/self-managed/operational-guides/production-guide.md
> +- Version Management: Stay on a stable Camunda and Kubernetes version. Follow Camunda’s release notes for security patches or critical updates. A list of our supported versions Camunda Helm Charts ca
There's nothing offhand that I can think of to prevent linking supported Helm chart versions on the environments page, especially if linking to the appropriate [Camunda version](https://helm.camunda.io/camunda-platform/version-matrix/camunda-8.6/) of the chart matrix there. 

@akeller does this sound feasible? I could make an issue for it, and this PR could just link to supported environments for now, e.g. just say "Supported Camunda versions can be found on the supported environments page".

2025-01-22 19:29 UTC, akeller commented on docs/self-managed/operational-guides/production-guide.md
> +- Version Management: Stay on a stable Camunda and Kubernetes version. Follow Camunda’s release notes for security patches or critical updates. A list of our supported versions Camunda Helm Charts ca
I really like this idea so we can isolate things we need to change frequently (like version mapping) to the supported environments page. 🟢 all good @conceptualshark

2025-01-22 23:18 UTC, akeller commented
Will this still ship with 8.7? Confirming all open PRs labeled with 8.7 that this is still correct.

Also, I'm not really into the idea of images as PDFs included in our docs repo. I see there are several already, but this PR also includes one. What's the intention here? (FYI @conceptualshark)

2025-01-24 23:29 UTC, aabouzaid requested changes
Great job @hamza-m-masood :clap: :clap: 

I've left a couple of minor comments.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +```
The code should be indented under the point that belongs to it.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +```
The language is missing `yaml`.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +For example, this is the default affinity configuration for the Core Pod in the Camunda Helm Chart:
The line should be indented under the point that belongs to it.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +- Make sure to not store any state or important, long term business data in the local file system of the container. A pod is transient, if the pod is restarted then the data will get wiped. It is bet
`pod` => `Pod`

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to have a pod security standard that is suitable to the security constraints you might have. This is possible through modifying the Pod Security Admission. Please refer to the [Kuber
For better readability, in the hyperlinks, let's use the page name instead using the generic name `Kubernetes documentation`.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to enable audit logging for Camunda components to track user actions, especially for sensitive data or configuration changes. Here is an example configuration to change the log level
What is the basis for this recommendation? In prod envs, it's probably less verbose log level is set.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +    name: "camunda-test-credentials"
Let's make quote usage more consistent.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +### Upgrade and Maintenance
Let's also add the point about following the upgrade guide before the actual upgrade.

2025-01-24 23:29 UTC, aabouzaid commented on docs/self-managed/operational-guides/production-guide.md
> +Make sure secrets are not auto-generated on upgrade.
We just need to mention that the secrets are not auto-generated on upgrade by default, and it's important not to override that.

2025-02-04 11:53 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +## Architecture Overview
This PR is specifically for 8.8
I will make another PR for 8.7

2025-02-04 12:50 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +This guide provides a simplified and streamlined architecture for core Camunda 8 applications using the Camunda Helm Chart. This setup minimizes complexity while offering a reliable foundation for mo
done

2025-02-04 13:51 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +This guide provides a simplified and streamlined architecture for core Camunda 8 applications using the Camunda Helm Chart. This setup minimizes complexity while offering a reliable foundation for mo
done

2025-02-04 13:52 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like to learn more about the architecture setup, please refer to the [About Self Managed](/docs/self-managed/about-self-managed/#architecture) and [Camunda 8 reference architectures](/do
rebased

2025-02-04 18:39 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like to learn more about the architecture setup, please refer to the [About Self Managed](/docs/self-managed/about-self-managed/#architecture) and [Camunda 8 reference architectures](/do
The link still does not work because it does not have the "next" in the path. I will not put this in the path because it won't be necessary when the next version is released. Am I correct here @conceptualshark ?

2025-02-04 18:42 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- **Helm**: Make sure you have the [Helm CLI](https://helm.sh/docs/intro/install/) installed
changed link

2025-02-04 18:43 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +  - **Amazon OpenSearch**: is used as a datastore for Camunda Orchestration Core components. Have a look at our guide for setting an [OpenSearch domain](/docs/self-managed/setup/deploy/amazon/amazon-
added

2025-02-04 18:48 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- **Persistent Volumes**: Configure block storage persistent volumes for stateful components.
Good point. I added this point to the k8s section

2025-02-04 18:58 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +This guide provides a simplified and streamlined architecture for core Camunda 8 applications using the Camunda Helm Chart. This setup minimizes complexity while offering a reliable foundation for mo
reworded

2025-02-04 19:04 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +# Step-by-Step Production Guide
I removed that heading because there is no way for me to add it in properly. Headings that are 3 levels deep do not show up on the sidebar.

2025-02-04 22:28 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Within the `management` namespace (Web Modeler and Console), we will install Identity, Console, and all the Web Modeler components. Within the `orchestration` namespace, we will install the Camunda O
done

2025-02-04 22:30 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +In order to access the Camunda Platform through HTTPS with Ingress, you have to enable TLS. To do that, you require three things:
done, thanks

2025-02-04 22:30 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Here is an example values.yaml configuration using the domain and TLS secret mentioned above:
done, thanks

2025-02-04 22:32 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Optionally, you can configure Ingress for Zeebe GRP endpoints. Here is an example Zeebe GRPC Ingress setup:
done, thanks

2025-02-04 22:36 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +core:
this guide will remain for 8.8, I will make sure to take this feedback into account for the new 8.7 PR

2025-02-04 22:37 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +At this point you would be able connect to your platform through HTTPS, correctly authenticate users using AWS Simple Active Directory, and have connected to external databases such as Amazon OpenSea
Thank you <3

2025-02-04 22:43 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +    host: "external-postgres-host"
I removed quotes from everywhere except where env vars are defined or where numbers should be treated like strings, for example in OIDC section

2025-02-04 23:09 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +The `existingSecret` can be used to specify an existing Kubernetes secret with the password.
Use the existingSecret parameter to specify a pre-existing Kubernetes secret containing the password5. This approach allows the Camunda Helm chart to reference credentials stored securely in your cluster rather than hardcoding sensitive data in values files or templates.

2025-02-04 23:09 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +The `existingSecret` can be used to specify an existing Kubernetes secret with the password.
I hope that is clear

2025-02-04 23:10 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +### Index Retention
I picked the second

2025-02-04 23:14 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like more information on configuring ILM policy. Please refer to [our guide](/self-managed/operate-deployment/data-retention.md).
Because I could not find one for zeebe

2025-02-04 23:19 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +If you would like more information on configuring ILM policy. Please refer to [our guide](/self-managed/operate-deployment/data-retention.md).
I just found something more related to zeebe. Maybe I can put this instead: [docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/opensearch-exporter/#configuration](https://docs.camunda.io/docs/next/self-managed/zeebe-deployment/exporters/opensearch-exporter/#configuration)

2025-02-04 23:27 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +```
I indented the yaml

2025-02-04 23:28 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +```
Good catch!!

2025-02-05 08:48 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +- It is possible to enable audit logging for Camunda components to track user actions, especially for sensitive data or configuration changes. Here is an example configuration to change the log level
You are right, I will remove it. It looks strange that I gave an audit logging example for one component.

2025-02-05 08:52 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +### Upgrade and Maintenance
Added

2025-02-05 08:53 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Make sure secrets are not auto-generated on upgrade.
I added that points, thanks

2025-02-05 15:13 UTC, Langleu requested changes
I left some comments where I found things still either confusing or vague.

I don't know whether we should do expectation management in the overview?
To a customer, the Helm chart is the first product they have in their hands to deploy Camunda 8.
Just because your Helm chart is production-ready does not necessarily mean your Camunda 8 installation is production-ready. From the epic, I also get the focus on helm, but maybe setting expectations could help, as customers don't look at it as two different products, which we internally do.
Customers may not associate the Camunda Helm chart as not being just Camunda 8 and I guess the guidance would be different.

Maybe also to reel in @theburi on the above.

I'm starting to see things come together, well done 🚀!

2025-02-06 16:31 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide.md
> +Make sure secrets are not auto-generated on upgrade.
I fixed some points around aut-generating secrets

2025-02-06 16:57 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +The next section will explain various configurations used in `production-values.yaml`.
Thanks, I will add it

2025-02-06 17:02 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +Once secure HTTPS connections are enabled and correctly configured via Ingress, the next stage to consider is configuring authentication. In this example, we will use AWS Simple Active Directory. Her
We are really just restating what is already mentioned int he AWS doc that is linked in prereq section

2025-02-06 17:30 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +It is expected that you already have one Amazon OpenSearch instance and two databases on Amazon Aurora PostgreSQL ready to use. Complete with a username, password, and URL. If not, refer to the guide
I thought about this at the start. My reasoning to not add IRSA was that this guide would become less beginner friendly. It is target more towards IT people who are new to Kubernetes and Helm and just want to know what it means to be production ready. 

I can mention IRSA but I am not comfortable in changing the examples to support IRSA. What do you think?

2025-02-06 17:32 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +- To scale the Core component, the following values can be modified:
I can add the sentence under the table to the guide. Not sure if I should add the table as well 🤔

2025-02-06 17:35 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +:::
Yeah good point. I can mention using Vault as an external secret manager

2025-02-06 17:55 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +:::
I also mentioned that it should be set to false on upgrade

2025-02-06 17:55 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +:::
I hope that is sufficient, please reopen if not

2025-02-06 17:56 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +```
Yes you are right. I was not finished the Bringing it all together section. That's why it does not seem that clear yet. I am nearly finished the values.yaml at the end.

2025-02-06 17:56 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +```
I will resolve this since i think the confusion here is no more. Please reopen if you have more points to make on this.

2025-02-07 09:03 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +- To scale the Core component, the following values can be modified:
You're right, I'd probably not mention the table.
The overprovisioning hint could be a good addition but it's also fine to leave it out, I guess different focus points. (Helm vs actual application)

2025-02-07 09:07 UTC, Langleu commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +It is expected that you already have one Amazon OpenSearch instance and two databases on Amazon Aurora PostgreSQL ready to use. Complete with a username, password, and URL. If not, refer to the guide
Sure, let's keep it out.

2025-02-10 08:52 UTC, hamza-m-masood commented on docs/self-managed/operational-guides/production-guide/helm-chart-production-guide.md
> +- **Amazon S3** - This will be used to store backups of the Camunda cluster. [Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html) must be configured with OpenSearch to take
I added your suggestion. This makes sense. Thank.

2025-02-10 08:56 UTC, hamza-m-masood commented
The only open item left in this doc is the last section called "Bringing it All Together"

I am getting some errors with getting multi-namespace and OIDC working at the same time.

2025-05-16 16:21 UTC, christinaausley commented
@hamza-m-masood Is this still in progress and planned for `8.8`?

2025-06-11 15:06 UTC, christinaausley commented
I see https://github.com/camunda/team-distribution/issues/344 is closed -- is this work still planned or should this PR be closed as well? CC @hisImminence @hamza-m-masood

2025-06-11 19:58 UTC, hamza-m-masood commented
@christinaausley sorry for having the PR open for so long. It is still planned to have a production guide for 8.8
The issue you linked is meant for 8.7.
I will have this PR merged soon.

2025-08-07 22:09 UTC, christinaausley commented
@hamza-m-masood Let me know if you need any support here or additional review 🚀

2025-09-03 18:38 UTC, christinaausley commented
Hi @hamza-m-masood -- is this still planned for 8.8?

2025-09-03 19:19 UTC, hisImminence commented
> Hi @hamza-m-masood -- is this still planned for 8.8?

Jumping in for Hamza here - this guide is still planned for 8.8. I updated the labels. Once we finish the migration work (1-2 weeks) - we will spend the rest of the time on doc updates.

2025-09-24 18:34 UTC, hisImminence commented
Duplicate of @jessesimpson36 [update for the production guide](https://github.com/camunda/camunda-docs/pull/6826). Will close this one!

2025-09-24 18:34 UTC, closed without merging