8.7.0-Alpha3 Release Notes
camunda/camunda-docs pull request #4759
Opened 2024-12-12 14:48 UTC by mesellings

## Description

8.7.0-Alpha3 Release Notes, based on [labeled epics](https://github.com/orgs/camunda/projects/9/views/31).

## When should this change go live?

- [ ] This is a bug fix, security concern, or something that needs **urgent release support**.
- [ ] This is already available but undocumented and should be released within a week.
- [ ] This on a **specific schedule** and the assignee will coordinate a release with the DevEx team. (apply `hold` label or convert to draft PR)
- [X] This is part of a scheduled alpha or minor. (apply alpha or minor label)
- [ ] There is **no urgency** with this change and can be released at any time.

## PR Checklist

- [ ] My changes are for an **already released minor** and are in `/versioned_docs` directory.
- [X] My changes are for the **next minor** and are in `/docs` directory (aka `/next/`).

- [X] My changes require an [Engineering review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned the Engineering DRI or delegate.
- [X] My changes require a [technical writer review](https://github.com/camunda/camunda-docs/blob/main/howtos/documentation-guidelines.md#review-process), and I've assigned @camunda/tech-writers as a reviewer.

2024-12-17 11:11 UTC, mesellings commented
FYI @akeller I've gone through and added all the potential items (and any content) into the release notes, and tagged the team in the #product-teams channel 👍

2024-12-17 15:06 UTC, akeller commented
@mesellings I tried to update the branch for you so the preview would build (build errors looked irrelevant to changes in this PR), but GitHub is experiencing an outage 😢

2025-01-08 14:12 UTC, mesellings commented
@akeller the release notes should have all entries now included and is ready for review please? 
- I will add some documentation links once the relevant docs are live (e.g. Connector docs).
- What should we do about the 8.7 release date mentioned on this page and in the main release notes page - I was going to wait until Friday to see what the decision is, but wasn't sure if you think we should do something else?

2025-01-08 20:30 UTC, akeller requested changes
I had a few nit-picks, including casing. Nothing jumped out at me that was missing, but I'm still catching up from FTO.

Re: the scheduled release date, let's sync internally later this week.

2025-01-08 20:30 UTC, akeller commented on docs/reference/release-notes/870.md
> +- Search: Search file items using the Box search API.
This is a little nitpicky, but I didn't like how this list looks on the preview site. I have two suggestions you can explore:

Bold the text to the left of the colon
> **Download File**: Download files into the Camunda document store.
(Following our style guide, I think this is actually needs to be lowercase "file" too.)

Or, remove the text to the left of the colon entirely.
> Download files into the Camunda document store.

This should be applied to the other Connector as well, but it jumped out at me in this longer list.

2025-01-08 20:30 UTC, akeller commented on docs/reference/release-notes/870.md
> +This Connector supports the following actions:
Nit-pick: Do Connectors have actions, operations, or both? And what is the difference? Can we standardize on this.

2025-01-08 20:30 UTC, akeller commented on docs/reference/release-notes/870.md
> +- The Document store API now supports uploading files in batches.
"The Document store API" casing looks a bit odd.

2025-01-08 20:30 UTC, akeller commented on docs/reference/release-notes/870.md
> +Enhanced Process Instance Migration now supports additional BPMN elements, enabling smoother transitions for your workflows and empowering operations teams to seamlessly migrate running process insta
```suggestion
Enhanced process instance migration now supports additional BPMN elements, enabling smoother transitions for your workflows and empowering operations teams to seamlessly migrate running process instances to updated process definitions without workarounds or manual intervention.
```

2025-01-09 10:41 UTC, mesellings commented on docs/reference/release-notes/870.md
> +- Search: Search file items using the Box search API.
Agreed, changed 👍

2025-01-09 10:42 UTC, mesellings commented on docs/reference/release-notes/870.md
> +This Connector supports the following actions:
I was checking with this, and yes Operations is the way to go, I've changed this - good spot! 🚀

2025-01-09 10:42 UTC, mesellings commented on docs/reference/release-notes/870.md
> +- The Document store API now supports uploading files in batches.
Agreed, changed 👍

2025-01-09 10:43 UTC, mesellings commented
Thanks @akeller I think I made all your suggested changes? 👍 🚀

2025-01-09 10:48 UTC, barmac commented on docs/reference/release-notes/870.md
> +### Ad-hoc subprocess BPMN pattern support <span class="badge badge--long" title="This feature affects SaaS">SaaS</span><span class="badge badge--long" title="This feature affects Self-Managed">Self-
This feature did not make it into the Modelers yet. You can deploy a hand-crafted XML to the engine, but you cannot model it in a diagram. I'd suggest to note it in the section explicitly, and we can announce the full support in the next alpha release notes as we are aiming to have modeling support by then.

2025-01-09 10:50 UTC, barmac commented on docs/reference/release-notes/870.md
> +User task events with the Zeebe user task implementation are renamed to "Camunda user tasks" and set as the default Modeler type.
```suggestion
User task implementation type "Zeebe user task" is renamed to "Camunda user task", and set as the default implementation type.
```

2025-01-09 10:53 UTC, barmac commented on docs/reference/release-notes/870.md
> +User task events with the Zeebe user task implementation are renamed to "Camunda user tasks" and set as the default Modeler type.
Old:

![image](https://github.com/user-attachments/assets/28057b11-f9cd-427f-818a-75502e694308)


New:
![image](https://github.com/user-attachments/assets/c1c87a52-e346-4f33-a711-4f047715ae13)

2025-01-09 11:33 UTC, mesellings commented on docs/reference/release-notes/870.md
> +### Ad-hoc subprocess BPMN pattern support <span class="badge badge--long" title="This feature affects SaaS">SaaS</span><span class="badge badge--long" title="This feature affects Self-Managed">Self-
Thanks @barmac - I added in a note - is this accurate?

> This release only supports manual deployment of the element to the engine via XML. Modeler support for this element is planned for the next alpha release.

2025-01-09 11:35 UTC, mesellings commented on docs/reference/release-notes/870.md
> +Job worker-based user tasks are now deprecated, with migration support provided to help you transition to the new type.
Thanks @barmac, would this be better as a note:

> Note: As Job-worker user tasks will be deprecated in Camunda 8.9, Camunda recommends you start using Camunda User Tasks (formerly known as Zeebe User Task) in your process definitions. To learn more, see [Announcements](https://docs.camunda.io/docs/next/reference/announcements/announcements-870/#deprecated-job-based-user-tasks-querying).

2025-01-10 10:18 UTC, mesellings commented
Removing entry for the BPMN ad-hoc subprocess as per request: https://github.com/camunda/product-hub/issues/2546#issuecomment-2582280201

`<!-- https://github.com/camunda/product-hub/issues/2546 -->

### Ad-hoc subprocess BPMN pattern support <span class="badge badge--long" title="This feature affects SaaS">SaaS</span><span class="badge badge--long" title="This feature affects Self-Managed">Self-Managed</span>

The ad-hoc subprocess BPMN element is now supported.

- This new kind of subprocess allows more flexible process flows with a compact visual representation.
- It is the first step towards dynamic processes and execution of ad-hoc activities.

:::note
This release only supports manual deployment of the element to the engine via XML. Modeler support for this element is planned for the next alpha release.
:::`

2025-01-10 11:27 UTC, mesellings commented
@barmac Are you able to check the two suggested notes please?
* https://github.com/camunda/camunda-docs/pull/4759#discussion_r1908622467
* https://github.com/camunda/camunda-docs/pull/4759#discussion_r1908619627

2025-01-10 12:05 UTC, barmac commented on docs/reference/release-notes/870.md
> +Job worker-based user tasks are now deprecated, with migration support provided to help you transition to the new type.
100% precise would be: 
> Note: As Job-worker user tasks managed by Camunda will be deprecated...

2025-01-10 12:05 UTC, barmac commented on docs/reference/release-notes/870.md
> +### Ad-hoc subprocess BPMN pattern support <span class="badge badge--long" title="This feature affects SaaS">SaaS</span><span class="badge badge--long" title="This feature affects Self-Managed">Self-
I assume this is outdated given https://github.com/camunda/camunda-docs/pull/4759#issuecomment-2582293910

2025-01-10 13:35 UTC, mesellings commented on docs/reference/release-notes/870.md
> +Job worker-based user tasks are now deprecated, with migration support provided to help you transition to the new type.
Thanks @barmac I've changed this note as per your feedback 🚀

2025-01-10 13:38 UTC, mesellings commented
@akeller Release notes should be final now (unless anything pulled/added) so just a decision on the date - I'm inclined to leave it as is until we have the final announcement on the 17th, wdyt? If you're happy with it, please can I get a final review/approval so it's ready to publish on Tuesday?

2025-01-13 17:22 UTC, akeller commented on docs/reference/release-notes/870.md
> +Camunda 8 Self-Managed now fully supports the use of Amazon OpenSearch with Optimize.
Hmm... following the trail from the epic I found https://github.com/camunda/camunda-docs/pull/4750/files where I can see the docs were just made a bit more generic. 

I can think of a couple ways we may want to address this:
* Relate this change back to Elasticsearch. Something that hints at why the parameter names used for OpenSearch may still retain the Elasticsearch name.
* Summarize the docs changes associated with this epic. Where the docs previously explained configuration exclusively for Elasticsearch, you'll find a generic reference to "the database" and can use either Elasticsearch or OpenSearch. 

Again, this can be a follow-up item if you want to sync with the implementation team. It just stood out to me that there was no link to the docs.

2025-01-14 08:39 UTC, merged

2025-01-14 15:53 UTC, mesellings commented on docs/reference/release-notes/870.md
> +Camunda 8 Self-Managed now fully supports the use of Amazon OpenSearch with Optimize.
I'll follow up with a PR for this 👍